$axure.loadCurrentPage({
  "url":"数据集详情-报表.html",
  "generationDate":new Date(1474274700342.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f37b97dc33b4a42848841e2440589b9",
    "type":"Axure:Page",
    "name":"数据集详情-报表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e577f78fdae45c3a9b0ac1b55a3f220",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"5542c2b03c214be0825ca9668913f769"},
{
          "id":"a7e9db6ed48749ffb93db8ae86a9d63d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":316,
              "y":5},
            "size":{
              "width":94,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8da51ba26384e8da8c66244e2035d20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":316,
                  "y":5},
                "size":{
                  "width":94,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u32.png"}},
{
          "id":"1da04f9767cf4d50ade8611915038ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":238,
              "y":17},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d027873e8f741c2adfd5b7ee4bfdd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":238,
                  "y":17},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10f589f193564391b960f8d59a515ccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":337,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb90f07b685d4740ad76277d53957a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":337,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1fab69763cc422fbe848f79b752ea5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":463,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a43b5d34a4c24ef9862c1bdfde4d571d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":463,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20f4484857dd4738aa67ee985b727562",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":590,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee6932c463f4633ac17784be8920316",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":590,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d35720efceab4cf7a78d4f45d019ad8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":123},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"369faa8fe7484ed882da2001d2326c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":123},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u56.png"}},
{
          "id":"f327ab52f18144ecacf80e7374bbedde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":100,
              "y":127},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f89fedfa20ea4952b925ec7402e11b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":100,
                  "y":127},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8742d6f1f93f4971a4a3eaa8b48de39b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":240},
            "size":{
              "width":1032,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/connector__/u60_line.png"}},
{
          "id":"c12f0ca2eb1b4f23aeb476e18d589c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":101,
              "y":154},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae7ee2556d284c07a392c9449174d447",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":101,
                  "y":154},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 添加connector in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"__connector.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e1a4d2dc844993a972e600944d39fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":127},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"109c96e35d6b4d368680cf7bd8894aaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":127},
                "size":{
                  "width":50,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 用户管理 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f863f1b1accb4e0686010720c0681ced",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":938.5,
              "y":133.5},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988617e5cb774561a079f59036b80d05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":938.5,
                  "y":133.5},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u79.png"}},
{
          "id":"ba784c19de22492c9856e6d48b36c375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":983.5,
              "y":134.5},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c50a32d613294efaa8aca1c0580cbb44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":983.5,
                  "y":134.5},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u94.png"}},
{
          "id":"34cdc40ed1c14cd19cf67846b6ade370",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":77},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a1c573aa62418ba7a262897773426f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":77},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99db3e3811bd4d23ac9066d5557a5010",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":69,
              "y":216},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c8c92327d894dbbba0b212d12ad20e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":69,
                  "y":216},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u55.png"}},
{
          "id":"8b7ccccf3a024fdead5cde17128ef19d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":216},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66e422ba39694c6aafdf588d52bcded1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":216},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u43.png"}},
{
          "id":"51abb0aa956a44d3af0764459d7ec2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":216},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20bfaec8278642aeb80b32aa908dd34c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":269,
                  "y":216},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u43.png"}},
{
          "id":"2cb182e4672d4d38816d7650223216a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":276},
            "size":{
              "width":180,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90afd7d7af2b41d38c80d05120d939bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":276},
                "size":{
                  "width":180,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u61.png"}},
{
          "id":"0d8f54e980a3408391d9854df45aaaf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":276},
            "size":{
              "width":180,
              "height":184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbaec11f751840e7b7b175e1d2796b06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":276},
                "size":{
                  "width":180,
                  "height":184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u63.png"}},
{
          "id":"fb2af9e0587a4c088b8609bf2f020d01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":276},
            "size":{
              "width":180,
              "height":184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037109b44e234a82bc11c42ad5514010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":276},
                "size":{
                  "width":180,
                  "height":184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u63.png"}},
{
          "id":"39ed2976784b402d9dfe4da033c8d3a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":276},
            "size":{
              "width":180,
              "height":184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a6a60fe9024ac69a95ba0e7123e6f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":276},
                "size":{
                  "width":180,
                  "height":184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u63.png"}},
{
          "id":"5e3e6a464e8b4f3497d8c3561bd5ff75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":330},
            "size":{
              "width":65,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9089f1e51a4a568cc226b4c43ef6a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":330},
                "size":{
                  "width":65,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u69.png"}},
{
          "id":"c2c3b80c8b3847f3b09501f3f3b4c0f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":425},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7ae7f00b384e42bf81e818d4886970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":425},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c32bdb3bb15489ba8554c0d6a37e9da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":282},
            "size":{
              "width":159,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6499e5d82d264b76973f1c1ed135ce19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":282},
                "size":{
                  "width":159,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 报表功能-图 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"报表功能-图.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/数据集详情-报表/u73.png"}},
{
          "id":"5244531e6894444badcb81f4f5eaed20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":282},
            "size":{
              "width":159,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f5e7089f23d4580ba172a49459539ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":282},
                "size":{
                  "width":159,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u75.png"}},
{
          "id":"e0f3fafa62d74f0ab476e65a6a8d682a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":282},
            "size":{
              "width":159,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3fa18bad03e47f2a37454a3299e7423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":282},
                "size":{
                  "width":159,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u77.png"}},
{
          "id":"6e5dcaabc8ac452f97d8a44e627aa121",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":460},
            "size":{
              "width":180,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1450a8c02584c43b77b06baa7608d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":460},
                "size":{
                  "width":180,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u79.png"}},
{
          "id":"6ad24e7483624306af0e320d305f28dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":460},
            "size":{
              "width":180,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cea39b5081a4d98a7da4ba757e8766e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":460},
                "size":{
                  "width":180,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u79.png"}},
{
          "id":"09097130a07c4d8e882fb1b0363ddf08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740.5,
              "y":460},
            "size":{
              "width":180,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0643befe10344a6829efda47a4930f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740.5,
                  "y":460},
                "size":{
                  "width":180,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u79.png"}},
{
          "id":"233626e8370e4c1aaa3ee98c81d9010b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":466},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c127d0ee52b5438191f72d54375cfda4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":466},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u94.png"}},
{
          "id":"0d5e47b5404049e2a5c3fb10a3dcc51b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":465},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85bd0d3279e6442589bb1c86e2fdb185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":465},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u28.png"}},
{
          "id":"5f37cb8952c34ab5b1b504d580031c48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":464},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b24e8a0420f244319820144f438b4fc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":464},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcf6d96e5e014480929a43db8a7940f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":465},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34cfa9519a0a48588a20718d74f662da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":465},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据集详情-报表/u91.png"}},
{
          "id":"ce0811cb57a4414894db52a473e040d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":662,
              "y":467},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d8d1328dee742a2b933b9aa0f910c87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":662,
                  "y":467},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u94.png"}},
{
          "id":"f2c9b40cbfdf4bfd815ca1c2562ae5df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":466},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52ebb25097dc4032a4175148bad263bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":466},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u28.png"}},
{
          "id":"6b8eb937e1874356bbe69305e0d95531",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":465},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d1ce71e5ef84bc4aee52d449782e42d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":465},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17333b9f2b264a628dd06bf73dc6c121",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":895,
              "y":467},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1398aafe459d494f84c491235b60743b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":895,
                  "y":467},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u94.png"}},
{
          "id":"f695abc97a2f4ab8a71c84cc1dcf2073",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":755,
              "y":466},
            "size":{
              "width":15,
              "height":15},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b29dc61e03f447dbe2ff0fc613a7b58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":755,
                  "y":466},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u28.png"}},
{
          "id":"c82bce43a9a8431ca4f54a77f53dac42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":465},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a061942e28754638bb831d4af1219739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":465},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "5542c2b03c214be0825ca9668913f769":{
      "packageId":"5542c2b03c214be0825ca9668913f769",
      "type":"Axure:Master",
      "name":"公共头部-已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u3.png"}},
{
            "id":"3bcafff37ae64af2bea60047cfc6b6d6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":15},
              "size":{
                "width":40,
                "height":40},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58e79641c93d441f861049198e19d942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1110,
                    "y":15},
                  "size":{
                    "width":40,
                    "height":40},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set 用户设置 to 菜单",
                        "panelsToStates":[{
                            "panelPath":["93eca07adb4e4fc4a41d614d18498197"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/connector__/u5.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3788ab7d7eb6473fb90f6b3d04c9d4a0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1054,
                "y":19},
              "size":{
                "width":35,
                "height":35},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fedf1a1b475d4ecd8c4286b504e1ecd2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1054,
                    "y":19},
                  "size":{
                    "width":35,
                    "height":35},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u9.png"}},
{
            "id":"3057107345934e169d773a87fd4ca5bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFF,
                "opacity":0},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":1075,
                "y":18},
              "size":{
                "width":10,
                "height":10},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a4c1ffc855e48eb89325e8821ce3673",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF,
                    "opacity":0},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":1075,
                    "y":18},
                  "size":{
                    "width":10,
                    "height":10},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u11.png"}},
{
            "id":"28baee9b1f8d490f84c240cd46dba014",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":238,
                "y":27},
              "size":{
                "width":29,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f183fe51e0764fe6aba4768b04474e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":238,
                    "y":27},
                  "size":{
                    "width":29,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"97dc0897c185427db74e6a3d9af0e4f4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aad64ad92a34411a81170d03e47b3695",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37187d0cb1cd4788aff96082b2fce88f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":463,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5990d77a0fed46efab899c51311831a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":463,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f714a97a54e2460985f688450813581f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":590,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a6babad0b20c4058ae55e4f79d5d8e90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":590,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"93eca07adb4e4fc4a41d614d18498197",
            "label":"用户设置",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":55},
              "size":{
                "width":140,
                "height":115}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"105d9e067c434de9882fa01917671576",
                "label":"null",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"b080cbd4cc694748aa3f7b2264e72103",
                "label":"菜单",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"42b31ce597d64e1fb85bc5a4fdd210dd",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":140,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fe776c44550c494992797a165259f471",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":140,
                            "height":120}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u22.png"}},
{
                    "id":"060533122f194eee8fbb0026893375b6",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":20},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bc5eacb229ca428b8591c2787768feb8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":20},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cbc3eeec59b24953b61c5b5d250862a8",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":60},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"04a58d5632a14fac89a109a4119b7c15",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":60},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 租户信息 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"租户信息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"430a0eeff6c54ed4bfb3c33b50af8441",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":21},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c09b8589ca346ba81e5a7a12f543362",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":21},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u28.png"}},
{
                    "id":"5a0767b803ff48b383c34492015edc99",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":60},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c7c54ebc78514d33bbcc9ade17e1599d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":60},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u30.png"}}]}]}]}}},
  "objectPaths":{
    "4e577f78fdae45c3a9b0ac1b55a3f220":{
      "scriptId":"u0",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u1"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u2"},
      "3bcafff37ae64af2bea60047cfc6b6d6":{
        "scriptId":"u3"},
      "58e79641c93d441f861049198e19d942":{
        "scriptId":"u4"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u5"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u6"},
      "3788ab7d7eb6473fb90f6b3d04c9d4a0":{
        "scriptId":"u7"},
      "fedf1a1b475d4ecd8c4286b504e1ecd2":{
        "scriptId":"u8"},
      "3057107345934e169d773a87fd4ca5bf":{
        "scriptId":"u9"},
      "0a4c1ffc855e48eb89325e8821ce3673":{
        "scriptId":"u10"},
      "28baee9b1f8d490f84c240cd46dba014":{
        "scriptId":"u11"},
      "f183fe51e0764fe6aba4768b04474e66":{
        "scriptId":"u12"},
      "97dc0897c185427db74e6a3d9af0e4f4":{
        "scriptId":"u13"},
      "aad64ad92a34411a81170d03e47b3695":{
        "scriptId":"u14"},
      "37187d0cb1cd4788aff96082b2fce88f":{
        "scriptId":"u15"},
      "5990d77a0fed46efab899c51311831a8":{
        "scriptId":"u16"},
      "f714a97a54e2460985f688450813581f":{
        "scriptId":"u17"},
      "a6babad0b20c4058ae55e4f79d5d8e90":{
        "scriptId":"u18"},
      "93eca07adb4e4fc4a41d614d18498197":{
        "scriptId":"u19"},
      "42b31ce597d64e1fb85bc5a4fdd210dd":{
        "scriptId":"u20"},
      "fe776c44550c494992797a165259f471":{
        "scriptId":"u21"},
      "060533122f194eee8fbb0026893375b6":{
        "scriptId":"u22"},
      "bc5eacb229ca428b8591c2787768feb8":{
        "scriptId":"u23"},
      "cbc3eeec59b24953b61c5b5d250862a8":{
        "scriptId":"u24"},
      "04a58d5632a14fac89a109a4119b7c15":{
        "scriptId":"u25"},
      "430a0eeff6c54ed4bfb3c33b50af8441":{
        "scriptId":"u26"},
      "1c09b8589ca346ba81e5a7a12f543362":{
        "scriptId":"u27"},
      "5a0767b803ff48b383c34492015edc99":{
        "scriptId":"u28"},
      "c7c54ebc78514d33bbcc9ade17e1599d":{
        "scriptId":"u29"}},
    "a7e9db6ed48749ffb93db8ae86a9d63d":{
      "scriptId":"u30"},
    "a8da51ba26384e8da8c66244e2035d20":{
      "scriptId":"u31"},
    "1da04f9767cf4d50ade8611915038ef2":{
      "scriptId":"u32"},
    "2d027873e8f741c2adfd5b7ee4bfdd4f":{
      "scriptId":"u33"},
    "10f589f193564391b960f8d59a515ccb":{
      "scriptId":"u34"},
    "eb90f07b685d4740ad76277d53957a9b":{
      "scriptId":"u35"},
    "c1fab69763cc422fbe848f79b752ea5d":{
      "scriptId":"u36"},
    "a43b5d34a4c24ef9862c1bdfde4d571d":{
      "scriptId":"u37"},
    "20f4484857dd4738aa67ee985b727562":{
      "scriptId":"u38"},
    "4ee6932c463f4633ac17784be8920316":{
      "scriptId":"u39"},
    "d35720efceab4cf7a78d4f45d019ad8c":{
      "scriptId":"u40"},
    "369faa8fe7484ed882da2001d2326c9d":{
      "scriptId":"u41"},
    "f327ab52f18144ecacf80e7374bbedde":{
      "scriptId":"u42"},
    "f89fedfa20ea4952b925ec7402e11b4e":{
      "scriptId":"u43"},
    "8742d6f1f93f4971a4a3eaa8b48de39b":{
      "scriptId":"u44"},
    "c12f0ca2eb1b4f23aeb476e18d589c9f":{
      "scriptId":"u45"},
    "ae7ee2556d284c07a392c9449174d447":{
      "scriptId":"u46"},
    "37e1a4d2dc844993a972e600944d39fa":{
      "scriptId":"u47"},
    "109c96e35d6b4d368680cf7bd8894aaf":{
      "scriptId":"u48"},
    "f863f1b1accb4e0686010720c0681ced":{
      "scriptId":"u49"},
    "988617e5cb774561a079f59036b80d05":{
      "scriptId":"u50"},
    "ba784c19de22492c9856e6d48b36c375":{
      "scriptId":"u51"},
    "c50a32d613294efaa8aca1c0580cbb44":{
      "scriptId":"u52"},
    "34cdc40ed1c14cd19cf67846b6ade370":{
      "scriptId":"u53"},
    "01a1c573aa62418ba7a262897773426f":{
      "scriptId":"u54"},
    "99db3e3811bd4d23ac9066d5557a5010":{
      "scriptId":"u55"},
    "7c8c92327d894dbbba0b212d12ad20e6":{
      "scriptId":"u56"},
    "8b7ccccf3a024fdead5cde17128ef19d":{
      "scriptId":"u57"},
    "66e422ba39694c6aafdf588d52bcded1":{
      "scriptId":"u58"},
    "51abb0aa956a44d3af0764459d7ec2de":{
      "scriptId":"u59"},
    "20bfaec8278642aeb80b32aa908dd34c":{
      "scriptId":"u60"},
    "2cb182e4672d4d38816d7650223216a2":{
      "scriptId":"u61"},
    "90afd7d7af2b41d38c80d05120d939bd":{
      "scriptId":"u62"},
    "0d8f54e980a3408391d9854df45aaaf2":{
      "scriptId":"u63"},
    "dbaec11f751840e7b7b175e1d2796b06":{
      "scriptId":"u64"},
    "fb2af9e0587a4c088b8609bf2f020d01":{
      "scriptId":"u65"},
    "037109b44e234a82bc11c42ad5514010":{
      "scriptId":"u66"},
    "39ed2976784b402d9dfe4da033c8d3a2":{
      "scriptId":"u67"},
    "a3a6a60fe9024ac69a95ba0e7123e6f7":{
      "scriptId":"u68"},
    "5e3e6a464e8b4f3497d8c3561bd5ff75":{
      "scriptId":"u69"},
    "bd9089f1e51a4a568cc226b4c43ef6a0":{
      "scriptId":"u70"},
    "c2c3b80c8b3847f3b09501f3f3b4c0f0":{
      "scriptId":"u71"},
    "9f7ae7f00b384e42bf81e818d4886970":{
      "scriptId":"u72"},
    "1c32bdb3bb15489ba8554c0d6a37e9da":{
      "scriptId":"u73"},
    "6499e5d82d264b76973f1c1ed135ce19":{
      "scriptId":"u74"},
    "5244531e6894444badcb81f4f5eaed20":{
      "scriptId":"u75"},
    "2f5e7089f23d4580ba172a49459539ee":{
      "scriptId":"u76"},
    "e0f3fafa62d74f0ab476e65a6a8d682a":{
      "scriptId":"u77"},
    "c3fa18bad03e47f2a37454a3299e7423":{
      "scriptId":"u78"},
    "6e5dcaabc8ac452f97d8a44e627aa121":{
      "scriptId":"u79"},
    "e1450a8c02584c43b77b06baa7608d92":{
      "scriptId":"u80"},
    "6ad24e7483624306af0e320d305f28dd":{
      "scriptId":"u81"},
    "1cea39b5081a4d98a7da4ba757e8766e":{
      "scriptId":"u82"},
    "09097130a07c4d8e882fb1b0363ddf08":{
      "scriptId":"u83"},
    "f0643befe10344a6829efda47a4930f5":{
      "scriptId":"u84"},
    "233626e8370e4c1aaa3ee98c81d9010b":{
      "scriptId":"u85"},
    "c127d0ee52b5438191f72d54375cfda4":{
      "scriptId":"u86"},
    "0d5e47b5404049e2a5c3fb10a3dcc51b":{
      "scriptId":"u87"},
    "85bd0d3279e6442589bb1c86e2fdb185":{
      "scriptId":"u88"},
    "5f37cb8952c34ab5b1b504d580031c48":{
      "scriptId":"u89"},
    "b24e8a0420f244319820144f438b4fc9":{
      "scriptId":"u90"},
    "fcf6d96e5e014480929a43db8a7940f6":{
      "scriptId":"u91"},
    "34cfa9519a0a48588a20718d74f662da":{
      "scriptId":"u92"},
    "ce0811cb57a4414894db52a473e040d9":{
      "scriptId":"u93"},
    "1d8d1328dee742a2b933b9aa0f910c87":{
      "scriptId":"u94"},
    "f2c9b40cbfdf4bfd815ca1c2562ae5df":{
      "scriptId":"u95"},
    "52ebb25097dc4032a4175148bad263bb":{
      "scriptId":"u96"},
    "6b8eb937e1874356bbe69305e0d95531":{
      "scriptId":"u97"},
    "4d1ce71e5ef84bc4aee52d449782e42d":{
      "scriptId":"u98"},
    "17333b9f2b264a628dd06bf73dc6c121":{
      "scriptId":"u99"},
    "1398aafe459d494f84c491235b60743b":{
      "scriptId":"u100"},
    "f695abc97a2f4ab8a71c84cc1dcf2073":{
      "scriptId":"u101"},
    "5b29dc61e03f447dbe2ff0fc613a7b58":{
      "scriptId":"u102"},
    "c82bce43a9a8431ca4f54a77f53dac42":{
      "scriptId":"u103"},
    "a061942e28754638bb831d4af1219739":{
      "scriptId":"u104"}}});