$axure.loadCurrentPage({
  "url":"组管理.html",
  "generationDate":new Date(1479293524492.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"301ae27243ea4f9cb7dded9b92b87fd1",
    "type":"Axure:Page",
    "name":"组管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"664565efba74482a9916b8ee650dee02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":50},
            "size":{
              "width":200,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f041922413948c58d1f49722e742d4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":50},
                "size":{
                  "width":200,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u0.png"}},
{
          "id":"814d4dd5b0084f809c592e11276b7352",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":110},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfba91b2916e4350884a91c4c4c4ebc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":110},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u2.png"}},
{
          "id":"4453fc2301d74638a259d4c6a769a2f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"5542c2b03c214be0825ca9668913f769"},
{
          "id":"1ed24294d6534dceb17d28744e3ccc79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":200,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f16b6f16d2745c6bc98f23b9bfb74da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":200,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u34.png"}},
{
          "id":"34b9acce5fc84c9c988096ac556a4f23",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":230,
              "y":60},
            "size":{
              "width":159,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9baaf26db510487f8bc7576233ac490e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":124},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"851861ae39634ca292ac85a4d2a13706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":124},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1992aa2b4c104c9fa9183f61b159a739",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":159},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a839c52157ac48c3895992d6dca1c4d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":159},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f92d2444fc2d4076af4fe33ffc47f07e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":50},
            "size":{
              "width":760,
              "height":730}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff496f2825a94e97b2976aedf6af897b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":50},
                "size":{
                  "width":760,
                  "height":730}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u41.png"}},
{
          "id":"925c1d32fdf04160a4f19b237ead4c20",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":420},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"2b95a80ea7fb4ee7be66b324293408a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":143},
            "size":{
              "width":760,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/用户管理/u58_line.png"}},
{
          "id":"7bbae4e401dc49fda1fc35d861860263",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":530,
              "y":80},
            "size":{
              "width":47,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d622f611a8af48d0ac40e65836d4a9cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":530,
                  "y":80},
                "size":{
                  "width":47,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62626e8c902d456ab2570272a6e8a22b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":440,
              "y":170},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cd28d7089a5413c887b6edd4e753cf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":440,
                  "y":170},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e65dfb137e264431926e10c913d2db8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":441,
              "y":340},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a804a2f37121411786ef296820b72605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":441,
                  "y":340},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c635e0d6e20495db735e6945989aaef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":56.5},
            "size":{
              "width":64,
              "height":63},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c02743031d98444ab6194f0937232f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":56.5},
                "size":{
                  "width":64,
                  "height":63},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u51.png"}},
{
          "id":"14afb340761f4e6e84b36142cb9e729d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":219},
            "size":{
              "width":45,
              "height":44},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68523a4f6d384536b046c93bacc314db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":219},
                "size":{
                  "width":45,
                  "height":44},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u16.png"}},
{
          "id":"b78ace447fe045cfa6cdea0941031abc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":269},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bffb955195a040ea9d3f269b5f55552d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":446,
                  "y":269},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb2b9eccc62c4baabd924f0c36394e8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":219},
            "size":{
              "width":45,
              "height":44},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"293013ca59a64bd8be447cc498380059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":531,
                  "y":219},
                "size":{
                  "width":45,
                  "height":44},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u16.png"}},
{
          "id":"937363fa478a462fa6e12c35ef1a5e8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":537,
              "y":269},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39bc14c538f34be080d46b094857c127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":537,
                  "y":269},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2655861f3ce64a288cb21fe50662bec4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":219},
            "size":{
              "width":45,
              "height":44},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32bc6e989832466d956fb58286b7f81c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":622,
                  "y":219},
                "size":{
                  "width":45,
                  "height":44},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u16.png"}},
{
          "id":"2a23f115ef184e70ad9902473c6b07bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":269},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8255e9f812314db1b6ef7b6d65195e25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":269},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2994e54a353040d4b6d69778c8543c20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":219},
            "size":{
              "width":45,
              "height":44},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a40bbe186ec847c1a5fdaf3a11580cac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":219},
                "size":{
                  "width":45,
                  "height":44},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u16.png"}},
{
          "id":"4d6d0101200d4ad3aa2f7d8d64007c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":269},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5516040817184227be0383c77985304f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":269},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"567ff9a749cf4798bb8031adc86c74dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":805,
              "y":219},
            "size":{
              "width":45,
              "height":44},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abe46e979e0c48b6b2b4f79a006c2877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":805,
                  "y":219},
                "size":{
                  "width":45,
                  "height":44},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u16.png"}},
{
          "id":"73a5e02026cc4a959c2feb0b28f7c4bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":811,
              "y":269},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21d9425ea6154fcfad5a776ee21a666b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":811,
                  "y":269},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27a42393813b464c9bade43c13412e8b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1010,
              "y":170},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"64cb2ab340414f6c9348b98403eac1e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":380},
            "size":{
              "width":700,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1564c78b1b5476c80f5068b5275f20e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":380},
                "size":{
                  "width":700,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u74.png"}},
{
          "id":"326d441fe92e4c008713f54dbbe7f430",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":455,
              "y":389},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb9f2a8a1786452e86da98e23e4246ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":455,
                  "y":389},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f587a969cc5b442482760d806bb365fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":464},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd79684b36742cc9cfeae62734802af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":464},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f59a22ac7cf445b93655bb070b20eab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":464},
            "size":{
              "width":27,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc44dc365c9b44e2a69cddb4d363ca36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":464},
                "size":{
                  "width":27,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u80.png"}},
{
          "id":"4ac15070f4d14b7aa94a9ec21df20569",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1010,
              "y":385},
            "size":{
              "width":70,
              "height":29}},
          "adaptiveStyles":{
}},
{
          "id":"7081cca103c44f15b58991947688f745",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1037,
              "y":466},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a04d4d5f7a184d6b95f386584fa9ba9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1037,
                  "y":466},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"588370d0683242499f2ed21388abf409",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":516},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e64cebcd96814f18be60efa61dd06a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":516},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a43d94b07134f229b822713f3c64cf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":516},
            "size":{
              "width":27,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8034875e94cc4e1a813c022d5915c212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":516},
                "size":{
                  "width":27,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u80.png"}},
{
          "id":"796ff2bb6b1a4d188e6b90295c65ed94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1037,
              "y":518},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b354902878a40799c3cd7871b63c2d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1037,
                  "y":518},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6b372da71de4d7d80064b1052c1fb5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":572},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dddab01c1824cdd8644e680c629859d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":572},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9223d9fca9c4c8ab41ee848d2094d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":572},
            "size":{
              "width":27,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74087f9b7b4d4e8dbe26337ced64dca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":572},
                "size":{
                  "width":27,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组管理/u80.png"}},
{
          "id":"2b829defb9224bcf842be203765a8478",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1037,
              "y":574},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcc79ecd61da44bf8fd0f203c9ec1c4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1037,
                  "y":574},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfd068f17c1a41dd9300f3baf031b1e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":80},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"569abde0ff714eb681591afee3496194",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":80},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u230.png"}},
{
          "id":"5a26d36e47944234b3b60b5d4b1c7d46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":124},
            "size":{
              "width":18,
              "height":18},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4618a5f639a547068c6378ded15ff35a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":458,
                  "y":124},
                "size":{
                  "width":18,
                  "height":18},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报表功能-图/u230.png"}},
{
          "id":"e544a599757a4fb0be02927ea09c4506",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":841,
              "y":172.5},
            "size":{
              "width":159,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"df95e37611f448fbb1ae437f10ec79a6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":831,
              "y":389},
            "size":{
              "width":159,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b4c76ec4edff4bed876f928a8bcef34f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":640,
              "y":730},
            "size":{
              "width":251,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"2336ffad9c4d4815821bcd2127217130",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":125},
            "size":{
              "width":140,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4748f661ae774c1faeb9405680f31483",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":140,
                  "height":90}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e3432196ff5444290f56154c5210ca2",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":140,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1bf323cfadc4583862425b0961f9700",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "size":{
                          "width":140,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/组管理/u106.png"}},
{
                  "id":"852966affbfc45308b388cbbb7041fc5",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0662aeacf6ce4fe487ec80f140fd7e71",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 组管理 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"组管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/组管理/u108.png"}},
{
                  "id":"01dec73e4b4a465abd53bc48a5226ee6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e8970fa7bb845358e6fbc9672fa9c5a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open 权限设置 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"权限设置.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/用户管理/u42.png"}}]}]},
{
          "id":"4a1cca9d01ac41d9ba8ea662c9d42bef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":72,
              "y":71},
            "size":{
              "width":56,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d9fb2bc9914a3d9cf85cedecc6be00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":72,
                  "y":71},
                "size":{
                  "width":56,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 租户信息 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"租户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d3a3aef3cc34d53b8afd9e2eb6d476b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":72},
            "size":{
              "width":52,
              "height":29},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8551fbede7f465bac588f6e8f64f75f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":72},
                "size":{
                  "width":52,
                  "height":29},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u95.png"}},
{
          "id":"3553c3820b2b4559ab229602d26130d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":432},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"725d65d4d99d4747a53212f41e68f241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":432},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcd1fddf3ff74d0bbf45c96bdb2b33bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":432},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"701dfad783cf4c44a0cd698766eb5010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":432},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b517f07e1f44d7a94cb3678e9f1d7df",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":468},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f7c82ac84324ca2b8db093dce132bee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":468},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e4157dfe2ae241908293ae6f5e204c1e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":468},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a7afecb8ff44566a6c8ab128cc0482c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":468},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9f27af992eb74988a4fdbeb5b29c1ec4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":520},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e879af8c81d64c22b73e92b0234c094c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":520},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"5eb891809db149109a7c7c32617dbac4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":520},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"661f63725c32403cafb733f74f90183e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":520},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ede437a2c68546d3aa00742ac3a5d2f3",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":576},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b763ce58bdb49edbb023b2332570643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":576},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3ef64033bc09489f8c590923abe722f6",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":831,
              "y":576},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a959968fca9944f8be39c1b450d5a29c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":831,
                  "y":576},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "5542c2b03c214be0825ca9668913f769":{
      "packageId":"5542c2b03c214be0825ca9668913f769",
      "type":"Axure:Master",
      "name":"公共头部-已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/报表功能-图/u14.png"}},
{
            "id":"3bcafff37ae64af2bea60047cfc6b6d6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":15},
              "size":{
                "width":40,
                "height":40},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58e79641c93d441f861049198e19d942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1110,
                    "y":15},
                  "size":{
                    "width":40,
                    "height":40},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set 用户设置 to 菜单",
                        "panelsToStates":[{
                            "panelPath":["93eca07adb4e4fc4a41d614d18498197"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/报表功能-图/u16.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3788ab7d7eb6473fb90f6b3d04c9d4a0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1054,
                "y":19},
              "size":{
                "width":35,
                "height":35},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fedf1a1b475d4ecd8c4286b504e1ecd2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1054,
                    "y":19},
                  "size":{
                    "width":35,
                    "height":35},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/报表功能-图/u20.png"}},
{
            "id":"3057107345934e169d773a87fd4ca5bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFF,
                "opacity":0},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":1075,
                "y":18},
              "size":{
                "width":10,
                "height":10},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a4c1ffc855e48eb89325e8821ce3673",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF,
                    "opacity":0},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":1075,
                    "y":18},
                  "size":{
                    "width":10,
                    "height":10},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/报表功能-图/u22.png"}},
{
            "id":"28baee9b1f8d490f84c240cd46dba014",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":238,
                "y":27},
              "size":{
                "width":29,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f183fe51e0764fe6aba4768b04474e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":238,
                    "y":27},
                  "size":{
                    "width":29,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open home-已登录 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home-___.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"97dc0897c185427db74e6a3d9af0e4f4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aad64ad92a34411a81170d03e47b3695",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 数据集列表 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"数据集列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37187d0cb1cd4788aff96082b2fce88f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":463,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5990d77a0fed46efab899c51311831a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":463,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f714a97a54e2460985f688450813581f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":590,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a6babad0b20c4058ae55e4f79d5d8e90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":590,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"93eca07adb4e4fc4a41d614d18498197",
            "label":"用户设置",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":55},
              "size":{
                "width":140,
                "height":115}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"105d9e067c434de9882fa01917671576",
                "label":"null",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"b080cbd4cc694748aa3f7b2264e72103",
                "label":"菜单",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"42b31ce597d64e1fb85bc5a4fdd210dd",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":140,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fe776c44550c494992797a165259f471",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":140,
                            "height":120}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/报表功能-图/u33.png"}},
{
                    "id":"060533122f194eee8fbb0026893375b6",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":20},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bc5eacb229ca428b8591c2787768feb8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":20},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cbc3eeec59b24953b61c5b5d250862a8",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":60},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"04a58d5632a14fac89a109a4119b7c15",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":60},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 租户信息 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"租户信息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"430a0eeff6c54ed4bfb3c33b50af8441",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":21},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c09b8589ca346ba81e5a7a12f543362",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":21},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/报表功能-图/u39.png"}},
{
                    "id":"5a0767b803ff48b383c34492015edc99",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":60},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c7c54ebc78514d33bbcc9ade17e1599d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":60},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/报表功能-图/u41.png"}}]}]}]}}},
  "objectPaths":{
    "664565efba74482a9916b8ee650dee02":{
      "scriptId":"u0"},
    "9f041922413948c58d1f49722e742d4f":{
      "scriptId":"u1"},
    "814d4dd5b0084f809c592e11276b7352":{
      "scriptId":"u2"},
    "bfba91b2916e4350884a91c4c4c4ebc9":{
      "scriptId":"u3"},
    "4453fc2301d74638a259d4c6a769a2f6":{
      "scriptId":"u4",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u5"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u6"},
      "3bcafff37ae64af2bea60047cfc6b6d6":{
        "scriptId":"u7"},
      "58e79641c93d441f861049198e19d942":{
        "scriptId":"u8"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u9"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u10"},
      "3788ab7d7eb6473fb90f6b3d04c9d4a0":{
        "scriptId":"u11"},
      "fedf1a1b475d4ecd8c4286b504e1ecd2":{
        "scriptId":"u12"},
      "3057107345934e169d773a87fd4ca5bf":{
        "scriptId":"u13"},
      "0a4c1ffc855e48eb89325e8821ce3673":{
        "scriptId":"u14"},
      "28baee9b1f8d490f84c240cd46dba014":{
        "scriptId":"u15"},
      "f183fe51e0764fe6aba4768b04474e66":{
        "scriptId":"u16"},
      "97dc0897c185427db74e6a3d9af0e4f4":{
        "scriptId":"u17"},
      "aad64ad92a34411a81170d03e47b3695":{
        "scriptId":"u18"},
      "37187d0cb1cd4788aff96082b2fce88f":{
        "scriptId":"u19"},
      "5990d77a0fed46efab899c51311831a8":{
        "scriptId":"u20"},
      "f714a97a54e2460985f688450813581f":{
        "scriptId":"u21"},
      "a6babad0b20c4058ae55e4f79d5d8e90":{
        "scriptId":"u22"},
      "93eca07adb4e4fc4a41d614d18498197":{
        "scriptId":"u23"},
      "42b31ce597d64e1fb85bc5a4fdd210dd":{
        "scriptId":"u24"},
      "fe776c44550c494992797a165259f471":{
        "scriptId":"u25"},
      "060533122f194eee8fbb0026893375b6":{
        "scriptId":"u26"},
      "bc5eacb229ca428b8591c2787768feb8":{
        "scriptId":"u27"},
      "cbc3eeec59b24953b61c5b5d250862a8":{
        "scriptId":"u28"},
      "04a58d5632a14fac89a109a4119b7c15":{
        "scriptId":"u29"},
      "430a0eeff6c54ed4bfb3c33b50af8441":{
        "scriptId":"u30"},
      "1c09b8589ca346ba81e5a7a12f543362":{
        "scriptId":"u31"},
      "5a0767b803ff48b383c34492015edc99":{
        "scriptId":"u32"},
      "c7c54ebc78514d33bbcc9ade17e1599d":{
        "scriptId":"u33"}},
    "1ed24294d6534dceb17d28744e3ccc79":{
      "scriptId":"u34"},
    "2f16b6f16d2745c6bc98f23b9bfb74da":{
      "scriptId":"u35"},
    "34b9acce5fc84c9c988096ac556a4f23":{
      "scriptId":"u36"},
    "9baaf26db510487f8bc7576233ac490e":{
      "scriptId":"u37"},
    "851861ae39634ca292ac85a4d2a13706":{
      "scriptId":"u38"},
    "1992aa2b4c104c9fa9183f61b159a739":{
      "scriptId":"u39"},
    "a839c52157ac48c3895992d6dca1c4d5":{
      "scriptId":"u40"},
    "f92d2444fc2d4076af4fe33ffc47f07e":{
      "scriptId":"u41"},
    "ff496f2825a94e97b2976aedf6af897b":{
      "scriptId":"u42"},
    "925c1d32fdf04160a4f19b237ead4c20":{
      "scriptId":"u43"},
    "2b95a80ea7fb4ee7be66b324293408a8":{
      "scriptId":"u44"},
    "7bbae4e401dc49fda1fc35d861860263":{
      "scriptId":"u45"},
    "d622f611a8af48d0ac40e65836d4a9cf":{
      "scriptId":"u46"},
    "62626e8c902d456ab2570272a6e8a22b":{
      "scriptId":"u47"},
    "0cd28d7089a5413c887b6edd4e753cf1":{
      "scriptId":"u48"},
    "e65dfb137e264431926e10c913d2db8b":{
      "scriptId":"u49"},
    "a804a2f37121411786ef296820b72605":{
      "scriptId":"u50"},
    "1c635e0d6e20495db735e6945989aaef":{
      "scriptId":"u51"},
    "c02743031d98444ab6194f0937232f01":{
      "scriptId":"u52"},
    "14afb340761f4e6e84b36142cb9e729d":{
      "scriptId":"u53"},
    "68523a4f6d384536b046c93bacc314db":{
      "scriptId":"u54"},
    "b78ace447fe045cfa6cdea0941031abc":{
      "scriptId":"u55"},
    "bffb955195a040ea9d3f269b5f55552d":{
      "scriptId":"u56"},
    "cb2b9eccc62c4baabd924f0c36394e8b":{
      "scriptId":"u57"},
    "293013ca59a64bd8be447cc498380059":{
      "scriptId":"u58"},
    "937363fa478a462fa6e12c35ef1a5e8e":{
      "scriptId":"u59"},
    "39bc14c538f34be080d46b094857c127":{
      "scriptId":"u60"},
    "2655861f3ce64a288cb21fe50662bec4":{
      "scriptId":"u61"},
    "32bc6e989832466d956fb58286b7f81c":{
      "scriptId":"u62"},
    "2a23f115ef184e70ad9902473c6b07bd":{
      "scriptId":"u63"},
    "8255e9f812314db1b6ef7b6d65195e25":{
      "scriptId":"u64"},
    "2994e54a353040d4b6d69778c8543c20":{
      "scriptId":"u65"},
    "a40bbe186ec847c1a5fdaf3a11580cac":{
      "scriptId":"u66"},
    "4d6d0101200d4ad3aa2f7d8d64007c95":{
      "scriptId":"u67"},
    "5516040817184227be0383c77985304f":{
      "scriptId":"u68"},
    "567ff9a749cf4798bb8031adc86c74dc":{
      "scriptId":"u69"},
    "abe46e979e0c48b6b2b4f79a006c2877":{
      "scriptId":"u70"},
    "73a5e02026cc4a959c2feb0b28f7c4bf":{
      "scriptId":"u71"},
    "21d9425ea6154fcfad5a776ee21a666b":{
      "scriptId":"u72"},
    "27a42393813b464c9bade43c13412e8b":{
      "scriptId":"u73"},
    "64cb2ab340414f6c9348b98403eac1e1":{
      "scriptId":"u74"},
    "a1564c78b1b5476c80f5068b5275f20e":{
      "scriptId":"u75"},
    "326d441fe92e4c008713f54dbbe7f430":{
      "scriptId":"u76"},
    "fb9f2a8a1786452e86da98e23e4246ea":{
      "scriptId":"u77"},
    "f587a969cc5b442482760d806bb365fc":{
      "scriptId":"u78"},
    "acd79684b36742cc9cfeae62734802af":{
      "scriptId":"u79"},
    "9f59a22ac7cf445b93655bb070b20eab":{
      "scriptId":"u80"},
    "cc44dc365c9b44e2a69cddb4d363ca36":{
      "scriptId":"u81"},
    "4ac15070f4d14b7aa94a9ec21df20569":{
      "scriptId":"u82"},
    "7081cca103c44f15b58991947688f745":{
      "scriptId":"u83"},
    "a04d4d5f7a184d6b95f386584fa9ba9c":{
      "scriptId":"u84"},
    "588370d0683242499f2ed21388abf409":{
      "scriptId":"u85"},
    "e64cebcd96814f18be60efa61dd06a91":{
      "scriptId":"u86"},
    "8a43d94b07134f229b822713f3c64cf3":{
      "scriptId":"u87"},
    "8034875e94cc4e1a813c022d5915c212":{
      "scriptId":"u88"},
    "796ff2bb6b1a4d188e6b90295c65ed94":{
      "scriptId":"u89"},
    "4b354902878a40799c3cd7871b63c2d3":{
      "scriptId":"u90"},
    "f6b372da71de4d7d80064b1052c1fb5f":{
      "scriptId":"u91"},
    "3dddab01c1824cdd8644e680c629859d":{
      "scriptId":"u92"},
    "e9223d9fca9c4c8ab41ee848d2094d9c":{
      "scriptId":"u93"},
    "74087f9b7b4d4e8dbe26337ced64dca5":{
      "scriptId":"u94"},
    "2b829defb9224bcf842be203765a8478":{
      "scriptId":"u95"},
    "dcc79ecd61da44bf8fd0f203c9ec1c4b":{
      "scriptId":"u96"},
    "dfd068f17c1a41dd9300f3baf031b1e5":{
      "scriptId":"u97"},
    "569abde0ff714eb681591afee3496194":{
      "scriptId":"u98"},
    "5a26d36e47944234b3b60b5d4b1c7d46":{
      "scriptId":"u99"},
    "4618a5f639a547068c6378ded15ff35a":{
      "scriptId":"u100"},
    "e544a599757a4fb0be02927ea09c4506":{
      "scriptId":"u101"},
    "df95e37611f448fbb1ae437f10ec79a6":{
      "scriptId":"u102"},
    "b4c76ec4edff4bed876f928a8bcef34f":{
      "scriptId":"u103"},
    "2336ffad9c4d4815821bcd2127217130":{
      "scriptId":"u104"},
    "4748f661ae774c1faeb9405680f31483":{
      "scriptId":"u105"},
    "0e3432196ff5444290f56154c5210ca2":{
      "scriptId":"u106"},
    "e1bf323cfadc4583862425b0961f9700":{
      "scriptId":"u107"},
    "852966affbfc45308b388cbbb7041fc5":{
      "scriptId":"u108"},
    "0662aeacf6ce4fe487ec80f140fd7e71":{
      "scriptId":"u109"},
    "01dec73e4b4a465abd53bc48a5226ee6":{
      "scriptId":"u110"},
    "0e8970fa7bb845358e6fbc9672fa9c5a":{
      "scriptId":"u111"},
    "4a1cca9d01ac41d9ba8ea662c9d42bef":{
      "scriptId":"u112"},
    "31d9fb2bc9914a3d9cf85cedecc6be00":{
      "scriptId":"u113"},
    "3d3a3aef3cc34d53b8afd9e2eb6d476b":{
      "scriptId":"u114"},
    "e8551fbede7f465bac588f6e8f64f75f":{
      "scriptId":"u115"},
    "3553c3820b2b4559ab229602d26130d2":{
      "scriptId":"u116"},
    "725d65d4d99d4747a53212f41e68f241":{
      "scriptId":"u117"},
    "dcd1fddf3ff74d0bbf45c96bdb2b33bb":{
      "scriptId":"u118"},
    "701dfad783cf4c44a0cd698766eb5010":{
      "scriptId":"u119"},
    "0b517f07e1f44d7a94cb3678e9f1d7df":{
      "scriptId":"u120"},
    "2f7c82ac84324ca2b8db093dce132bee":{
      "scriptId":"u121"},
    "e4157dfe2ae241908293ae6f5e204c1e":{
      "scriptId":"u122"},
    "8a7afecb8ff44566a6c8ab128cc0482c":{
      "scriptId":"u123"},
    "9f27af992eb74988a4fdbeb5b29c1ec4":{
      "scriptId":"u124"},
    "e879af8c81d64c22b73e92b0234c094c":{
      "scriptId":"u125"},
    "5eb891809db149109a7c7c32617dbac4":{
      "scriptId":"u126"},
    "661f63725c32403cafb733f74f90183e":{
      "scriptId":"u127"},
    "ede437a2c68546d3aa00742ac3a5d2f3":{
      "scriptId":"u128"},
    "6b763ce58bdb49edbb023b2332570643":{
      "scriptId":"u129"},
    "3ef64033bc09489f8c590923abe722f6":{
      "scriptId":"u130"},
    "a959968fca9944f8be39c1b450d5a29c":{
      "scriptId":"u131"}}});