$axure.loadCurrentPage({
  "url":"用户注册流程.html",
  "generationDate":new Date(1479293541210.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6db92ff2ad7f45c29b810d24398e72e8",
    "type":"Axure:Page",
    "name":"用户注册流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"139dca39e9c04f70984c5fccb59f8022",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":120},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1338997506a84f7cbbe8f894d5fc1d43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":120},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u0.png"}},
{
          "id":"a5aeea7489cb452babaa0c1707bd95c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":165},
            "size":{
              "width":50,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/用户注册流程/u2_line.png"}},
{
          "id":"c0de987044784277b73dc3b62cc56985",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":120},
            "size":{
              "width":170,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33e6962f75094f28a2df8488cdb1b63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":120},
                "size":{
                  "width":170,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u3.png"}},
{
          "id":"4a40678d20a6449185f211ce9af42301",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":140},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"416586e65cd3407e9e4470cbaa1b9e50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":140},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u5.png"}},
{
          "id":"e225e9fd0ef64b5b8166e890d420fcd6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":165},
            "size":{
              "width":70,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/用户注册流程/u7_end.png",
            "line~":"images/用户注册流程/u7_line.png"}},
{
          "id":"5b636eae582b4ae79a9c4ba0651e51c8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":165},
            "size":{
              "width":200,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/用户注册流程/u7_end.png",
            "line~":"images/用户注册流程/u8_line.png"}},
{
          "id":"e5f9fa640cc44fb8b43e23c3359b4f18",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":755,
              "y":200},
            "size":{
              "width":10,
              "height":100}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/用户注册流程/u9_end.png",
            "line~":"images/用户注册流程/u9_line.png"}},
{
          "id":"a08e7909ab1040bbba680df7d71e8583",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":140},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dad288bc08c422a8369e2a9ec951214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":840,
                  "y":140},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac68a53cce074f5cbeadb2bab0b7604f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71495f129519483a8d218615d101dce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"ae06a7d3f6c74c3b90c30345997483aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":579,
              "y":44},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e577ca40d884dccb3f4bc692f37411e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":579,
                  "y":44},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cea95c0687144016aaf0251b5760dd27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":250},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00ed2f3e1f7544ab9b0eb73f99945d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":250},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47b38328c483471ca2dd0225c4564106",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":300},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"397a8bdc7e0e46609b51a45b290f29c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":300},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u0.png"}},
{
          "id":"749b05fda9e44d47900b5abb3a9feaa9",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":400},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cf80d580d0341438aabd20308e8346c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":400},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"f95379410b3d4eb898ed37c9b703bbeb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":480},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f20488f79c04159b633008fb881d230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":480},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u5.png"}},
{
          "id":"e36bd616a3654918a6918e9277384e2f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"201656ac0de34972b44eebd5be6c7c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"be87d3ba137b4ea8acec386777ac11d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":490},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09d7d31b0b249f39e253f6da99370d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":490},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f8c4cdbec70417da5f2164d8ef16b86",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5947790c8a3c44048f7031eabd481861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"21dc8a8531684cbca4e4532fd27ff3c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":460},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d9b3c350cfb4ccc8f320adda7cb6bf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":460},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u0.png"}},
{
          "id":"98be7c275c364ea5b47e36eb55d8a74a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1010,
              "y":129},
            "size":{
              "width":130,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fe722a7020c4bc796e8a724e8e5b32f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1010,
                  "y":129},
                "size":{
                  "width":130,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u32.png"}},
{
          "id":"a0e4bc700e984d108edb36fff6b96f8d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1136,
              "y":165},
            "size":{
              "width":90,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/用户注册流程/u7_end.png",
            "line~":"images/用户注册流程/u34_line.png"}},
{
          "id":"ff7cab02998d4eb6998ff60b78b22a22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1226,
              "y":129},
            "size":{
              "width":124,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cbc52efee8249c29504397f428f8589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1226,
                  "y":129},
                "size":{
                  "width":124,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u35.png"}},
{
          "id":"0a73fffd78af464c906a594b5e994eb4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1350,
              "y":167},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"251e7e2e2ab645b186d9bcae54b3d529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1350,
                  "y":167},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffd6b7643ac2479ab61d0f6148770539",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1410,
              "y":140},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d34108961042a7ab78a7e924ef35f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1410,
                  "y":140},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户注册流程/u39.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "139dca39e9c04f70984c5fccb59f8022":{
      "scriptId":"u0"},
    "1338997506a84f7cbbe8f894d5fc1d43":{
      "scriptId":"u1"},
    "a5aeea7489cb452babaa0c1707bd95c4":{
      "scriptId":"u2"},
    "c0de987044784277b73dc3b62cc56985":{
      "scriptId":"u3"},
    "33e6962f75094f28a2df8488cdb1b63e":{
      "scriptId":"u4"},
    "4a40678d20a6449185f211ce9af42301":{
      "scriptId":"u5"},
    "416586e65cd3407e9e4470cbaa1b9e50":{
      "scriptId":"u6"},
    "e225e9fd0ef64b5b8166e890d420fcd6":{
      "scriptId":"u7"},
    "5b636eae582b4ae79a9c4ba0651e51c8":{
      "scriptId":"u8"},
    "e5f9fa640cc44fb8b43e23c3359b4f18":{
      "scriptId":"u9"},
    "a08e7909ab1040bbba680df7d71e8583":{
      "scriptId":"u10"},
    "3dad288bc08c422a8369e2a9ec951214":{
      "scriptId":"u11"},
    "ac68a53cce074f5cbeadb2bab0b7604f":{
      "scriptId":"u12"},
    "71495f129519483a8d218615d101dce3":{
      "scriptId":"u13"},
    "ae06a7d3f6c74c3b90c30345997483aa":{
      "scriptId":"u14"},
    "1e577ca40d884dccb3f4bc692f37411e":{
      "scriptId":"u15"},
    "cea95c0687144016aaf0251b5760dd27":{
      "scriptId":"u16"},
    "00ed2f3e1f7544ab9b0eb73f99945d8a":{
      "scriptId":"u17"},
    "47b38328c483471ca2dd0225c4564106":{
      "scriptId":"u18"},
    "397a8bdc7e0e46609b51a45b290f29c6":{
      "scriptId":"u19"},
    "749b05fda9e44d47900b5abb3a9feaa9":{
      "scriptId":"u20"},
    "4cf80d580d0341438aabd20308e8346c":{
      "scriptId":"u21"},
    "f95379410b3d4eb898ed37c9b703bbeb":{
      "scriptId":"u22"},
    "2f20488f79c04159b633008fb881d230":{
      "scriptId":"u23"},
    "e36bd616a3654918a6918e9277384e2f":{
      "scriptId":"u24"},
    "201656ac0de34972b44eebd5be6c7c5a":{
      "scriptId":"u25"},
    "be87d3ba137b4ea8acec386777ac11d8":{
      "scriptId":"u26"},
    "c09d7d31b0b249f39e253f6da99370d8":{
      "scriptId":"u27"},
    "7f8c4cdbec70417da5f2164d8ef16b86":{
      "scriptId":"u28"},
    "5947790c8a3c44048f7031eabd481861":{
      "scriptId":"u29"},
    "21dc8a8531684cbca4e4532fd27ff3c8":{
      "scriptId":"u30"},
    "1d9b3c350cfb4ccc8f320adda7cb6bf3":{
      "scriptId":"u31"},
    "98be7c275c364ea5b47e36eb55d8a74a":{
      "scriptId":"u32"},
    "3fe722a7020c4bc796e8a724e8e5b32f":{
      "scriptId":"u33"},
    "a0e4bc700e984d108edb36fff6b96f8d":{
      "scriptId":"u34"},
    "ff7cab02998d4eb6998ff60b78b22a22":{
      "scriptId":"u35"},
    "7cbc52efee8249c29504397f428f8589":{
      "scriptId":"u36"},
    "0a73fffd78af464c906a594b5e994eb4":{
      "scriptId":"u37"},
    "251e7e2e2ab645b186d9bcae54b3d529":{
      "scriptId":"u38"},
    "ffd6b7643ac2479ab61d0f6148770539":{
      "scriptId":"u39"},
    "95d34108961042a7ab78a7e924ef35f0":{
      "scriptId":"u40"}}});