$axure.loadCurrentPage({
  "url":"登录信息.html",
  "generationDate":new Date(1477023113726.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"efe32aef5fa444e3a5e21ee3244c2fae",
    "type":"Axure:Page",
    "name":"登录信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF999999},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa4612389fb340b48fdc00d0eff973c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":98},
            "size":{
              "width":500,
              "height":442}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"821bf0fc104945a3b6249066890c9215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":98},
                "size":{
                  "width":500,
                  "height":442}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录信息/u0.png"}},
{
          "id":"144e6dce43a34a2bb6e430dbdad893a2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7"},
{
          "id":"b7eb0f59f73f4d059b6d36bc9d848a22",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":215},
            "size":{
              "width":280,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"299e8e4942574ed09281c17097d4f3af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":310},
            "size":{
              "width":460,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"d8fe14ea32c94f59977b7d653ba694c5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":680,
              "y":406},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open home-已登录 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home-___.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"aa71e8c882dc4b57bf8c0604eafeddec",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":406},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"17e0d77058a64ae3b0326cba3cc9f47b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":338,
              "y":474},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70afe868fee1461a945b0db9ffb17476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":338,
                  "y":474},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28be5ebdd1c54b3bb62ab68d01006649",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":140},
            "size":{
              "width":500,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录信息/u19_line.png"}},
{
          "id":"0028df4b59e64d5fb91620719c34348f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":114},
            "size":{
              "width":151,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069a9de1acac467ea4b6dae2d141ae95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":114},
                "size":{
                  "width":151,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6613fd6a8cc43c98cb651547770186a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":610,
              "y":215},
            "size":{
              "width":180,
              "height":45}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "d4bd2a6cc6e24b23b8d6d38fcc34aed7":{
      "packageId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7",
      "type":"Axure:Master",
      "name":"公共头部-未登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u3.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ad14925c042b4db492a9dc53a684564b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":1,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2ce2d4cce76a46e19ee0025bf6c804cd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":1,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1fd4ec783504405199fab72366944f1c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":883,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"abb3a0d0af25457da4d7531349b26a56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":883,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"113be51b57834160b0f9284e99716c61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1092,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1bacc409ead9433899b32306bde07311",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1092,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "fa4612389fb340b48fdc00d0eff973c8":{
      "scriptId":"u0"},
    "821bf0fc104945a3b6249066890c9215":{
      "scriptId":"u1"},
    "144e6dce43a34a2bb6e430dbdad893a2":{
      "scriptId":"u2",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u3"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u4"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u5"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u6"},
      "ad14925c042b4db492a9dc53a684564b":{
        "scriptId":"u7"},
      "2ce2d4cce76a46e19ee0025bf6c804cd":{
        "scriptId":"u8"},
      "1fd4ec783504405199fab72366944f1c":{
        "scriptId":"u9"},
      "abb3a0d0af25457da4d7531349b26a56":{
        "scriptId":"u10"},
      "113be51b57834160b0f9284e99716c61":{
        "scriptId":"u11"},
      "1bacc409ead9433899b32306bde07311":{
        "scriptId":"u12"}},
    "b7eb0f59f73f4d059b6d36bc9d848a22":{
      "scriptId":"u13"},
    "299e8e4942574ed09281c17097d4f3af":{
      "scriptId":"u14"},
    "d8fe14ea32c94f59977b7d653ba694c5":{
      "scriptId":"u15"},
    "aa71e8c882dc4b57bf8c0604eafeddec":{
      "scriptId":"u16"},
    "17e0d77058a64ae3b0326cba3cc9f47b":{
      "scriptId":"u17"},
    "70afe868fee1461a945b0db9ffb17476":{
      "scriptId":"u18"},
    "28be5ebdd1c54b3bb62ab68d01006649":{
      "scriptId":"u19"},
    "0028df4b59e64d5fb91620719c34348f":{
      "scriptId":"u20"},
    "069a9de1acac467ea4b6dae2d141ae95":{
      "scriptId":"u21"},
    "c6613fd6a8cc43c98cb651547770186a":{
      "scriptId":"u22"}}});