$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1473305302101.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"86e150e7f3a9412da81bb9bf60ca05a6",
    "type":"Axure:Page",
    "name":"home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7fd0f852d8c14bfebdd78b7fa23f1369",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7"},
{
          "id":"f9e755ea5c244baa9a721f9c6f89b827",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":293},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"044caa5562634e80998f14f29c21961e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":293},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d4bd2a6cc6e24b23b8d6d38fcc34aed7":{
      "packageId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7",
      "type":"Axure:Master",
      "name":"公共头部-未登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u1.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"115b930e5b274526aca9e35ab884857c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1059,
                "y":27},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f0b3794292364e43b3dc1db4cb16f645",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1059,
                    "y":27},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 用户登录 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"用户登录.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a5668640b32a4f16981daa9d3f514551",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1130,
                "y":27},
              "size":{
                "width":27,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8ca04e37d12a4a85816d944d89e7d8ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1130,
                    "y":27},
                  "size":{
                    "width":27,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 创建租户 in New Window/Tab",
                        "target":{
                          "targetType":"page",
                          "url":"创建租户.html",
                          "includeVariables":true},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "7fd0f852d8c14bfebdd78b7fa23f1369":{
      "scriptId":"u0",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u1"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u2"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u3"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u4"},
      "115b930e5b274526aca9e35ab884857c":{
        "scriptId":"u5"},
      "f0b3794292364e43b3dc1db4cb16f645":{
        "scriptId":"u6"},
      "a5668640b32a4f16981daa9d3f514551":{
        "scriptId":"u7"},
      "8ca04e37d12a4a85816d944d89e7d8ed":{
        "scriptId":"u8"}},
    "f9e755ea5c244baa9a721f9c6f89b827":{
      "scriptId":"u9"},
    "044caa5562634e80998f14f29c21961e":{
      "scriptId":"u10"}}});