$axure.loadCurrentPage({
  "url":"添加新的数据集.html",
  "generationDate":new Date(1474876934963.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"baf6474424364f41a56d934c16512169",
    "type":"Axure:Page",
    "name":"添加新的数据集",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"79006635523f495c8be17591d4b4d4f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"5542c2b03c214be0825ca9668913f769"},
{
          "id":"8e32edc47a9a4a018a9d3a06ee4c8f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":316,
              "y":5},
            "size":{
              "width":94,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e64da9f31f54d23af4d4b6b1666a1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":316,
                  "y":5},
                "size":{
                  "width":94,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u32.png"}},
{
          "id":"4ed39a9849304a18bd4eaf57c3c1be70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":238,
              "y":17},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2865a9a969f4b3d940a0efad5806798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":238,
                  "y":17},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0996fc24852641f7961f34a74754b095",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":337,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9c5be30fe0424889240815b5d4638f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":337,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cc8aa6a01f9474e9a004a8e42d2ed5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":463,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbb6424043f04834a86e6483d7623492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":463,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fb997e009fd4111a0b8fe8e35d373f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":590,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5fd9f79a1ad4457b991092f96c03368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":590,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9902680da724b7ba534308bd631c0af",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":110},
            "size":{
              "width":1060,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/connector__/u42_line.png"}},
{
          "id":"c0172a50b75e4c88b1c3ac9bb64e2419",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":73},
            "size":{
              "width":110,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54617edb9c644e18abc3c8e162aead2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":73},
                "size":{
                  "width":110,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新的数据集/u41.png"}},
{
          "id":"9701cecb3e964d9db7414ada16a49961",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":42,
              "y":248},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2ee0750bcb548f79ca9cb1c05ed4d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":42,
                  "y":248},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f481bc0dbd4c4b0cb2af608d94ac0d88",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":289},
            "size":{
              "width":343,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"9ccc307b41c645cab1e2d6a44ac8f3a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":42,
              "y":369},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2817f20da4f64fa0b69a1a68c2dd70cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":42,
                  "y":369},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e5110c95a204af2a0f3a8beac384e84",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":415},
            "size":{
              "width":911,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0d795c11cc9469da014f2e6c52f99c8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":304,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76d0f618b7854a3085a95ce8726fea95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":304,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u49.png"}},
{
              "id":"d50444fdcba54cf6a4ec29dfd0ed5ae1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":304,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39633ce95f7a4001ae44616e2420280b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":304,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u49.png"}},
{
              "id":"b5c69198cd7045e59132e030778da8db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":304,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd8598a76ce944eba384042e2368067f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":304,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u61.png"}},
{
              "id":"7fd93000168e4134b014f92b5b3e70d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":304,
                  "y":0},
                "size":{
                  "width":304,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90d8e68cd0774b52bf41314abc337ecb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":304,
                      "y":0},
                    "size":{
                      "width":304,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u49.png"}},
{
              "id":"59f98b8b124840808f316a360488c382",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":304,
                  "y":30},
                "size":{
                  "width":304,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6053167d893440d8d4cc5c4bbb433aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":304,
                      "y":30},
                    "size":{
                      "width":304,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u49.png"}},
{
              "id":"10bb5c8c1d464434a67c8088e5926414",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":304,
                  "y":60},
                "size":{
                  "width":304,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c118af91960491daa04cb15cf9f6e6c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":304,
                      "y":60},
                    "size":{
                      "width":304,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u61.png"}},
{
              "id":"18650c2e06984940afcda1c072311b77",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":608,
                  "y":0},
                "size":{
                  "width":303,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be3de2109b004e298944ff597c0173aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":608,
                      "y":0},
                    "size":{
                      "width":303,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u53.png"}},
{
              "id":"e63727f639de48b29308677266f7e8f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":608,
                  "y":30},
                "size":{
                  "width":303,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d71ab90e6bb453ea7329737382897a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":608,
                      "y":30},
                    "size":{
                      "width":303,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u53.png"}},
{
              "id":"990cbf23775e449aaa8b2b9bfb4a7f53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":608,
                  "y":60},
                "size":{
                  "width":303,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"338e58ee04774fb8a9b96933748085ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":608,
                      "y":60},
                    "size":{
                      "width":303,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加新的数据集/u65.png"}}]},
{
          "id":"28e5201916024e319f22a433b9ceb88b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":129,
              "y":240},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c253e9bed6f4a53870f1d109eab9fd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":129,
                  "y":240},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新的数据集/u67.png"}},
{
          "id":"7245a12a8c1941cc93f0b6f1fec9c23a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":73},
            "size":{
              "width":110,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d332509f4a2e41e3881667d21971390c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":73},
                "size":{
                  "width":110,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加新的数据集/u41.png"}},
{
          "id":"cc4ddfdd391f4146bd6d5ea76a65a83d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":246},
            "size":{
              "width":10,
              "height":20},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加新的数据集/u71_line.png"}},
{
          "id":"a163b9be6a8d4264b9970b906691289b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":365},
            "size":{
              "width":10,
              "height":20},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加新的数据集/u71_line.png"}},
{
          "id":"13b1916246374d8ba0a5105acd2e5a88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":40,
              "y":137},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069cd8c5acb14289954a6ecb0c925525",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":40,
                  "y":137},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a9b2ec99ef745f9be326c58a8681f2a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":135},
            "size":{
              "width":10,
              "height":20},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC00}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/添加新的数据集/u71_line.png"}},
{
          "id":"a76b09f45e0749f381fec798f693433a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":42,
              "y":175},
            "size":{
              "width":347,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"03562a43e1d14061857bc53b22180a2d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":69.5},
            "size":{
              "width":243,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"4a0231ea47b44760b59d586386be1eb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":39,
              "y":78},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bcd4a4b047b4ca081231a8ea71bdea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":39,
                  "y":78},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "5542c2b03c214be0825ca9668913f769":{
      "packageId":"5542c2b03c214be0825ca9668913f769",
      "type":"Axure:Master",
      "name":"公共头部-已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u3.png"}},
{
            "id":"3bcafff37ae64af2bea60047cfc6b6d6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":15},
              "size":{
                "width":40,
                "height":40},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58e79641c93d441f861049198e19d942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1110,
                    "y":15},
                  "size":{
                    "width":40,
                    "height":40},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set 用户设置 to 菜单",
                        "panelsToStates":[{
                            "panelPath":["93eca07adb4e4fc4a41d614d18498197"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/connector__/u5.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3788ab7d7eb6473fb90f6b3d04c9d4a0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1054,
                "y":19},
              "size":{
                "width":35,
                "height":35},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fedf1a1b475d4ecd8c4286b504e1ecd2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1054,
                    "y":19},
                  "size":{
                    "width":35,
                    "height":35},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u9.png"}},
{
            "id":"3057107345934e169d773a87fd4ca5bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFF,
                "opacity":0},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":1075,
                "y":18},
              "size":{
                "width":10,
                "height":10},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a4c1ffc855e48eb89325e8821ce3673",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF,
                    "opacity":0},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":1075,
                    "y":18},
                  "size":{
                    "width":10,
                    "height":10},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u11.png"}},
{
            "id":"28baee9b1f8d490f84c240cd46dba014",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":238,
                "y":27},
              "size":{
                "width":29,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f183fe51e0764fe6aba4768b04474e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":238,
                    "y":27},
                  "size":{
                    "width":29,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"97dc0897c185427db74e6a3d9af0e4f4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aad64ad92a34411a81170d03e47b3695",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37187d0cb1cd4788aff96082b2fce88f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":463,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5990d77a0fed46efab899c51311831a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":463,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f714a97a54e2460985f688450813581f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":590,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a6babad0b20c4058ae55e4f79d5d8e90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":590,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"93eca07adb4e4fc4a41d614d18498197",
            "label":"用户设置",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":55},
              "size":{
                "width":140,
                "height":115}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"105d9e067c434de9882fa01917671576",
                "label":"null",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"b080cbd4cc694748aa3f7b2264e72103",
                "label":"菜单",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"42b31ce597d64e1fb85bc5a4fdd210dd",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":140,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fe776c44550c494992797a165259f471",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":140,
                            "height":120}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u22.png"}},
{
                    "id":"060533122f194eee8fbb0026893375b6",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":20},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bc5eacb229ca428b8591c2787768feb8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":20},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cbc3eeec59b24953b61c5b5d250862a8",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":60},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"04a58d5632a14fac89a109a4119b7c15",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":60},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 租户信息 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"租户信息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"430a0eeff6c54ed4bfb3c33b50af8441",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":21},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c09b8589ca346ba81e5a7a12f543362",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":21},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u28.png"}},
{
                    "id":"5a0767b803ff48b383c34492015edc99",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":60},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c7c54ebc78514d33bbcc9ade17e1599d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":60},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u30.png"}}]}]}]}}},
  "objectPaths":{
    "79006635523f495c8be17591d4b4d4f6":{
      "scriptId":"u0",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u1"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u2"},
      "3bcafff37ae64af2bea60047cfc6b6d6":{
        "scriptId":"u3"},
      "58e79641c93d441f861049198e19d942":{
        "scriptId":"u4"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u5"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u6"},
      "3788ab7d7eb6473fb90f6b3d04c9d4a0":{
        "scriptId":"u7"},
      "fedf1a1b475d4ecd8c4286b504e1ecd2":{
        "scriptId":"u8"},
      "3057107345934e169d773a87fd4ca5bf":{
        "scriptId":"u9"},
      "0a4c1ffc855e48eb89325e8821ce3673":{
        "scriptId":"u10"},
      "28baee9b1f8d490f84c240cd46dba014":{
        "scriptId":"u11"},
      "f183fe51e0764fe6aba4768b04474e66":{
        "scriptId":"u12"},
      "97dc0897c185427db74e6a3d9af0e4f4":{
        "scriptId":"u13"},
      "aad64ad92a34411a81170d03e47b3695":{
        "scriptId":"u14"},
      "37187d0cb1cd4788aff96082b2fce88f":{
        "scriptId":"u15"},
      "5990d77a0fed46efab899c51311831a8":{
        "scriptId":"u16"},
      "f714a97a54e2460985f688450813581f":{
        "scriptId":"u17"},
      "a6babad0b20c4058ae55e4f79d5d8e90":{
        "scriptId":"u18"},
      "93eca07adb4e4fc4a41d614d18498197":{
        "scriptId":"u19"},
      "42b31ce597d64e1fb85bc5a4fdd210dd":{
        "scriptId":"u20"},
      "fe776c44550c494992797a165259f471":{
        "scriptId":"u21"},
      "060533122f194eee8fbb0026893375b6":{
        "scriptId":"u22"},
      "bc5eacb229ca428b8591c2787768feb8":{
        "scriptId":"u23"},
      "cbc3eeec59b24953b61c5b5d250862a8":{
        "scriptId":"u24"},
      "04a58d5632a14fac89a109a4119b7c15":{
        "scriptId":"u25"},
      "430a0eeff6c54ed4bfb3c33b50af8441":{
        "scriptId":"u26"},
      "1c09b8589ca346ba81e5a7a12f543362":{
        "scriptId":"u27"},
      "5a0767b803ff48b383c34492015edc99":{
        "scriptId":"u28"},
      "c7c54ebc78514d33bbcc9ade17e1599d":{
        "scriptId":"u29"}},
    "8e32edc47a9a4a018a9d3a06ee4c8f34":{
      "scriptId":"u30"},
    "1e64da9f31f54d23af4d4b6b1666a1dc":{
      "scriptId":"u31"},
    "4ed39a9849304a18bd4eaf57c3c1be70":{
      "scriptId":"u32"},
    "d2865a9a969f4b3d940a0efad5806798":{
      "scriptId":"u33"},
    "0996fc24852641f7961f34a74754b095":{
      "scriptId":"u34"},
    "3f9c5be30fe0424889240815b5d4638f":{
      "scriptId":"u35"},
    "8cc8aa6a01f9474e9a004a8e42d2ed5e":{
      "scriptId":"u36"},
    "dbb6424043f04834a86e6483d7623492":{
      "scriptId":"u37"},
    "4fb997e009fd4111a0b8fe8e35d373f7":{
      "scriptId":"u38"},
    "f5fd9f79a1ad4457b991092f96c03368":{
      "scriptId":"u39"},
    "c9902680da724b7ba534308bd631c0af":{
      "scriptId":"u40"},
    "c0172a50b75e4c88b1c3ac9bb64e2419":{
      "scriptId":"u41"},
    "54617edb9c644e18abc3c8e162aead2b":{
      "scriptId":"u42"},
    "9701cecb3e964d9db7414ada16a49961":{
      "scriptId":"u43"},
    "c2ee0750bcb548f79ca9cb1c05ed4d8a":{
      "scriptId":"u44"},
    "f481bc0dbd4c4b0cb2af608d94ac0d88":{
      "scriptId":"u45"},
    "9ccc307b41c645cab1e2d6a44ac8f3a5":{
      "scriptId":"u46"},
    "2817f20da4f64fa0b69a1a68c2dd70cc":{
      "scriptId":"u47"},
    "5e5110c95a204af2a0f3a8beac384e84":{
      "scriptId":"u48"},
    "c0d795c11cc9469da014f2e6c52f99c8":{
      "scriptId":"u49"},
    "76d0f618b7854a3085a95ce8726fea95":{
      "scriptId":"u50"},
    "7fd93000168e4134b014f92b5b3e70d9":{
      "scriptId":"u51"},
    "90d8e68cd0774b52bf41314abc337ecb":{
      "scriptId":"u52"},
    "18650c2e06984940afcda1c072311b77":{
      "scriptId":"u53"},
    "be3de2109b004e298944ff597c0173aa":{
      "scriptId":"u54"},
    "d50444fdcba54cf6a4ec29dfd0ed5ae1":{
      "scriptId":"u55"},
    "39633ce95f7a4001ae44616e2420280b":{
      "scriptId":"u56"},
    "59f98b8b124840808f316a360488c382":{
      "scriptId":"u57"},
    "f6053167d893440d8d4cc5c4bbb433aa":{
      "scriptId":"u58"},
    "e63727f639de48b29308677266f7e8f6":{
      "scriptId":"u59"},
    "6d71ab90e6bb453ea7329737382897a2":{
      "scriptId":"u60"},
    "b5c69198cd7045e59132e030778da8db":{
      "scriptId":"u61"},
    "fd8598a76ce944eba384042e2368067f":{
      "scriptId":"u62"},
    "10bb5c8c1d464434a67c8088e5926414":{
      "scriptId":"u63"},
    "9c118af91960491daa04cb15cf9f6e6c":{
      "scriptId":"u64"},
    "990cbf23775e449aaa8b2b9bfb4a7f53":{
      "scriptId":"u65"},
    "338e58ee04774fb8a9b96933748085ad":{
      "scriptId":"u66"},
    "28e5201916024e319f22a433b9ceb88b":{
      "scriptId":"u67"},
    "4c253e9bed6f4a53870f1d109eab9fd5":{
      "scriptId":"u68"},
    "7245a12a8c1941cc93f0b6f1fec9c23a":{
      "scriptId":"u69"},
    "d332509f4a2e41e3881667d21971390c":{
      "scriptId":"u70"},
    "cc4ddfdd391f4146bd6d5ea76a65a83d":{
      "scriptId":"u71"},
    "a163b9be6a8d4264b9970b906691289b":{
      "scriptId":"u72"},
    "13b1916246374d8ba0a5105acd2e5a88":{
      "scriptId":"u73"},
    "069cd8c5acb14289954a6ecb0c925525":{
      "scriptId":"u74"},
    "7a9b2ec99ef745f9be326c58a8681f2a":{
      "scriptId":"u75"},
    "a76b09f45e0749f381fec798f693433a":{
      "scriptId":"u76"},
    "03562a43e1d14061857bc53b22180a2d":{
      "scriptId":"u77"},
    "4a0231ea47b44760b59d586386be1eb6":{
      "scriptId":"u78"},
    "2bcd4a4b047b4ca081231a8ea71bdea5":{
      "scriptId":"u79"}}});