$axure.loadCurrentPage({
  "url":"弹窗.html",
  "generationDate":new Date(1476669363870.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e8734ac99db466e9cb0f3fc33a41817",
    "type":"Axure:Page",
    "name":"弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d73323327b3f40b9b907b5c4a5603374",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":400,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f6191fb540f4abea8ff38490963ab70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":400,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/弹窗/u0.png"}},
{
          "id":"9ccd50b88cd846eebb7865d31623602c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":158,
              "y":134},
            "size":{
              "width":272,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e90933244848f2b9a18c919af9e561",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":134},
                "size":{
                  "width":272,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a3c3267bb2d4cb7a83c5e471b877e55",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":285},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c1d0a96ea7f8462cafc005be6c69e275",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":285},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d73323327b3f40b9b907b5c4a5603374":{
      "scriptId":"u0"},
    "2f6191fb540f4abea8ff38490963ab70":{
      "scriptId":"u1"},
    "9ccd50b88cd846eebb7865d31623602c":{
      "scriptId":"u2"},
    "47e90933244848f2b9a18c919af9e561":{
      "scriptId":"u3"},
    "8a3c3267bb2d4cb7a83c5e471b877e55":{
      "scriptId":"u4"},
    "c1d0a96ea7f8462cafc005be6c69e275":{
      "scriptId":"u5"}}});