$axure.loadCurrentPage({
  "url":"创建租户.html",
  "generationDate":new Date(1479293522228.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2d40a80313b24fddbe0a57187fb1fbad",
    "type":"Axure:Page",
    "name":"创建租户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF999999},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1a4a847b0979409dae43b503e8137078",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":190,
              "y":260},
            "size":{
              "width":490,
              "height":52}},
          "adaptiveStyles":{
}},
{
          "id":"ef318659000e495fa5b7f91190a36a58",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":266},
            "size":{
              "width":190,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 设置域名 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"设置域名.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set 已存在提示 to 已存在",
                      "panelsToStates":[{
                          "panelPath":["136830a1e847428d9b1e6ae13b28d8cc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"9edfffdf982b446b90eeda6551e6a642",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7"},
{
          "id":"136830a1e847428d9b1e6ae13b28d8cc",
          "label":"已存在提示",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":342},
            "size":{
              "width":701,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d9453ce889974daeb453866fff8f023b",
              "label":"null",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"df28bf14b2b9419e9e48bec329700ddc",
              "label":"已存在",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"82e7ea946b3946fe80a57c5fa71e68bc",
                  "label":"",
                  "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":670,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"651e91bc702446f48d94d746375d4831",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":670,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建租户/u23.png"}},
{
                  "id":"2d2588b013c342df85bc25bf7e7850d1",
                  "label":"",
                  "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":38,
                      "y":14},
                    "size":{
                      "width":160,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfe40fb6e71241b9bd68a5f50abf9521",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":38,
                          "y":14},
                        "size":{
                          "width":160,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"28820b6e1a4b4579b77e56278f657178",
              "label":"team存在",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"70669dddcb664bb1850a33d321b25104",
                  "label":"",
                  "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":670,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5357b58dc7d34fe1a2007670b99d66a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":670,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建租户/u27.png"}},
{
                  "id":"bf897f8851d440b98cff105c642436fa",
                  "label":"",
                  "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":38,
                      "y":14},
                    "size":{
                      "width":160,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94092b6f48fe4609ac2623bf0a7504d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"136830a1e847428d9b1e6ae13b28d8cc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":38,
                          "y":14},
                        "size":{
                          "width":160,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "d4bd2a6cc6e24b23b8d6d38fcc34aed7":{
      "packageId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7",
      "type":"Axure:Master",
      "name":"公共头部-未登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/报表功能-图/u14.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ad14925c042b4db492a9dc53a684564b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":1,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2ce2d4cce76a46e19ee0025bf6c804cd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":1,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1fd4ec783504405199fab72366944f1c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":883,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"abb3a0d0af25457da4d7531349b26a56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":883,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"113be51b57834160b0f9284e99716c61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1092,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1bacc409ead9433899b32306bde07311",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1092,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"68eab370385048a19e61141abb8aafdd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":120},
              "size":{
                "width":820,
                "height":390}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1128c33bb77e419b925768169fd0bade",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":120},
                  "size":{
                    "width":820,
                    "height":390}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/创建租户/u13.png"}},
{
            "id":"fd8d8dada7be4c1585271200f70cf7bf",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":440,
                "y":245},
              "size":{
                "width":340,
                "height":45}},
            "adaptiveStyles":{
}},
{
            "id":"d8753c61dba7441cb388c4b822a91531",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":331,
                "y":260},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4038df99a0d743cb92726fec406865d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":331,
                    "y":260},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cbc86dfc21ad4493aa3fdfe776683054",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":440,
                "y":330},
              "size":{
                "width":340,
                "height":30},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"04b4b98378364eb28495596f370336e9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":440,
                    "y":330},
                  "size":{
                    "width":340,
                    "height":30},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Popup Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"popup",
                        "popup":{
                          "left":100,
                          "top":100,
                          "width":500,
                          "height":500,
                          "toolbar":false,
                          "scrollbars":false,
                          "location":false,
                          "status":false,
                          "menubar":false,
                          "directories":false,
                          "resizable":false,
                          "centerwindow":true}},
{
                        "action":"linkWindow",
                        "description":"Open 修改密码 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"修改密码.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/创建租户/u18.png"}},
{
            "id":"e7f5d69bae4b49f8af2433cf6d84faf9",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontWeight":"400",
              "location":{
                "x":232,
                "y":132},
              "size":{
                "width":97,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"679cd039b01b4cfba9dc26729e03e1fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontWeight":"400",
                  "location":{
                    "x":232,
                    "y":132},
                  "size":{
                    "width":97,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "1a4a847b0979409dae43b503e8137078":{
      "scriptId":"u0"},
    "ef318659000e495fa5b7f91190a36a58":{
      "scriptId":"u1"},
    "9edfffdf982b446b90eeda6551e6a642":{
      "scriptId":"u2",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u3"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u4"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u5"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u6"},
      "ad14925c042b4db492a9dc53a684564b":{
        "scriptId":"u7"},
      "2ce2d4cce76a46e19ee0025bf6c804cd":{
        "scriptId":"u8"},
      "1fd4ec783504405199fab72366944f1c":{
        "scriptId":"u9"},
      "abb3a0d0af25457da4d7531349b26a56":{
        "scriptId":"u10"},
      "113be51b57834160b0f9284e99716c61":{
        "scriptId":"u11"},
      "1bacc409ead9433899b32306bde07311":{
        "scriptId":"u12"},
      "68eab370385048a19e61141abb8aafdd":{
        "scriptId":"u13"},
      "1128c33bb77e419b925768169fd0bade":{
        "scriptId":"u14"},
      "fd8d8dada7be4c1585271200f70cf7bf":{
        "scriptId":"u15"},
      "d8753c61dba7441cb388c4b822a91531":{
        "scriptId":"u16"},
      "4038df99a0d743cb92726fec406865d4":{
        "scriptId":"u17"},
      "cbc86dfc21ad4493aa3fdfe776683054":{
        "scriptId":"u18"},
      "04b4b98378364eb28495596f370336e9":{
        "scriptId":"u19"},
      "e7f5d69bae4b49f8af2433cf6d84faf9":{
        "scriptId":"u20"},
      "679cd039b01b4cfba9dc26729e03e1fa":{
        "scriptId":"u21"}},
    "136830a1e847428d9b1e6ae13b28d8cc":{
      "scriptId":"u22"},
    "82e7ea946b3946fe80a57c5fa71e68bc":{
      "scriptId":"u23"},
    "651e91bc702446f48d94d746375d4831":{
      "scriptId":"u24"},
    "2d2588b013c342df85bc25bf7e7850d1":{
      "scriptId":"u25"},
    "bfe40fb6e71241b9bd68a5f50abf9521":{
      "scriptId":"u26"},
    "70669dddcb664bb1850a33d321b25104":{
      "scriptId":"u27"},
    "5357b58dc7d34fe1a2007670b99d66a4":{
      "scriptId":"u28"},
    "bf897f8851d440b98cff105c642436fa":{
      "scriptId":"u29"},
    "94092b6f48fe4609ac2623bf0a7504d9":{
      "scriptId":"u30"}}});