$axure.loadCurrentPage({
  "url":"忘记密码验证邮箱.html",
  "generationDate":new Date(1479373817604.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"31faab59f343473ca9b55ae13beafa76",
    "type":"Axure:Page",
    "name":"忘记密码验证邮箱",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e8bd92b6e90f46a1a91fca5dc54363ba",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7"},
{
          "id":"d267d7559bcd49e69bd0c7e72820626b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":120},
            "size":{
              "width":798,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d897ba1e21b418b97ab62732b55ad28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":120},
                "size":{
                  "width":798,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码验证邮箱/u11.png"}},
{
          "id":"edfc90ac3880495d83a26643ea5a373a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":230,
              "y":132},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a63ee901453418fbcc2f0a863894391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":230,
                  "y":132},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a4f7b8a34904aeaa2da426d7985e2f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":264},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f1d61a33824fc5b61952676286bdef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":264},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c80f492a5e543c890268886d2d403fa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":405,
              "y":250},
            "size":{
              "width":495,
              "height":50}},
          "adaptiveStyles":{
}},
{
          "id":"9f4a6906ec8f48d0ab54a5313455c9b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":350},
            "size":{
              "width":340,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3874f5a3883d45bba39c0c3ca629f48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":350},
                "size":{
                  "width":340,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 修改密码 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"修改密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/忘记密码验证邮箱/u18.png"}},
{
          "id":"f676b3537ed64d40b9253c746e99eab4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":405,
              "y":310},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b201eb520004493bef3528c047db14c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":405,
                  "y":310},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d4bd2a6cc6e24b23b8d6d38fcc34aed7":{
      "packageId":"d4bd2a6cc6e24b23b8d6d38fcc34aed7",
      "type":"Axure:Master",
      "name":"公共头部-未登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/报表功能-图/u14.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ad14925c042b4db492a9dc53a684564b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":1,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2ce2d4cce76a46e19ee0025bf6c804cd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":1,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1fd4ec783504405199fab72366944f1c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":883,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"abb3a0d0af25457da4d7531349b26a56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":883,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"113be51b57834160b0f9284e99716c61",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1092,
                "y":27},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1bacc409ead9433899b32306bde07311",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1092,
                    "y":27},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "e8bd92b6e90f46a1a91fca5dc54363ba":{
      "scriptId":"u0",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u1"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u2"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u3"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u4"},
      "ad14925c042b4db492a9dc53a684564b":{
        "scriptId":"u5"},
      "2ce2d4cce76a46e19ee0025bf6c804cd":{
        "scriptId":"u6"},
      "1fd4ec783504405199fab72366944f1c":{
        "scriptId":"u7"},
      "abb3a0d0af25457da4d7531349b26a56":{
        "scriptId":"u8"},
      "113be51b57834160b0f9284e99716c61":{
        "scriptId":"u9"},
      "1bacc409ead9433899b32306bde07311":{
        "scriptId":"u10"}},
    "d267d7559bcd49e69bd0c7e72820626b":{
      "scriptId":"u11"},
    "6d897ba1e21b418b97ab62732b55ad28":{
      "scriptId":"u12"},
    "edfc90ac3880495d83a26643ea5a373a":{
      "scriptId":"u13"},
    "2a63ee901453418fbcc2f0a863894391":{
      "scriptId":"u14"},
    "9a4f7b8a34904aeaa2da426d7985e2f6":{
      "scriptId":"u15"},
    "22f1d61a33824fc5b61952676286bdef":{
      "scriptId":"u16"},
    "7c80f492a5e543c890268886d2d403fa":{
      "scriptId":"u17"},
    "9f4a6906ec8f48d0ab54a5313455c9b9":{
      "scriptId":"u18"},
    "3874f5a3883d45bba39c0c3ca629f48f":{
      "scriptId":"u19"},
    "f676b3537ed64d40b9253c746e99eab4":{
      "scriptId":"u20"},
    "0b201eb520004493bef3528c047db14c":{
      "scriptId":"u21"}}});