$axure.loadCurrentPage({
  "url":"添加新的数据集-code.html",
  "generationDate":new Date(1476669358047.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"95c9d9789e8b4ef2a6a35d3f7947a439",
    "type":"Axure:Page",
    "name":"添加新的数据集-CODE",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ca573c50a3a64d9db2529eacf5104b69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":28,
              "y":127},
            "size":{
              "width":1002,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c549d8773a4361be4db2bdc2dbb6d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":28,
                  "y":127},
                "size":{
                  "width":1002,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__connector-mysql/u0.png"}},
{
          "id":"79006635523f495c8be17591d4b4d4f6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"5542c2b03c214be0825ca9668913f769"},
{
          "id":"8e32edc47a9a4a018a9d3a06ee4c8f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":316,
              "y":5},
            "size":{
              "width":94,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e64da9f31f54d23af4d4b6b1666a1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":316,
                  "y":5},
                "size":{
                  "width":94,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u32.png"}},
{
          "id":"4ed39a9849304a18bd4eaf57c3c1be70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":238,
              "y":17},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2865a9a969f4b3d940a0efad5806798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":238,
                  "y":17},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0996fc24852641f7961f34a74754b095",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":337,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9c5be30fe0424889240815b5d4638f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":337,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cc8aa6a01f9474e9a004a8e42d2ed5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":463,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbb6424043f04834a86e6483d7623492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":463,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fb997e009fd4111a0b8fe8e35d373f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":590,
              "y":17},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5fd9f79a1ad4457b991092f96c03368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":590,
                  "y":17},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78fd0bfe454740f287a830dfa71dd7ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":28,
              "y":71},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbaa83e228ef4c5ca0fec92fc49c219d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":28,
                  "y":71},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fccbcd2560d843e9834de44ae79c9f3d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":97},
            "size":{
              "width":402,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/__connector-mysql/u44_line.png"}},
{
          "id":"c0172a50b75e4c88b1c3ac9bb64e2419",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":77},
            "size":{
              "width":140,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54617edb9c644e18abc3c8e162aead2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":77},
                "size":{
                  "width":140,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u52.png"}},
{
          "id":"a2a747cf133c4e8ab60b02838b27f581",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":48,
              "y":137},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2ef16542ed4ab1966b910ababc57f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":48,
                  "y":137},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c642930c5b084844a0fa2e2ee738c6d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":28,
              "y":250},
            "size":{
              "width":1002,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e6a1f4f0c054426b70a1e3c8b0c478d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":28,
                  "y":250},
                "size":{
                  "width":1002,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__connector-mysql/u0.png"}},
{
          "id":"115990202db9497ead1635456794ce36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":48,
              "y":260},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53aef586ae204894a3b7cf6bb76746cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":48,
                  "y":260},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"058ad97e9437426c98f1eebd4d7b6766",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":983,
              "y":127},
            "size":{
              "width":40,
              "height":40},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0762b1c0f4204857bf9b328d7fa824b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":983,
                  "y":127},
                "size":{
                  "width":40,
                  "height":40},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__connector-mysql/u62.png"}},
{
          "id":"1df6057aa46646b4a1d592a42034c5aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":256},
            "size":{
              "width":30,
              "height":30},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"175e03766e81480f989ac3bbfd53a631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":990,
                  "y":256},
                "size":{
                  "width":30,
                  "height":30},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/__connector-mysql/u64.png"}},
{
          "id":"9686845298c34cfda2293503aef3c429",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":389,
              "y":70},
            "size":{
              "width":20,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1cbdcfa2e874416980e56484234da2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":389,
                  "y":70},
                "size":{
                  "width":20,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u77.png"}},
{
          "id":"7245a12a8c1941cc93f0b6f1fec9c23a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":77},
            "size":{
              "width":140,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d332509f4a2e41e3881667d21971390c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":77},
                "size":{
                  "width":140,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/connector__/u52.png"}},
{
          "id":"ead7c49a4c6e4efca0484170694b25fd",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":190},
            "size":{
              "width":352,
              "height":33}},
          "adaptiveStyles":{
}},
{
          "id":"00120108bf904733a8ed0fbe8f9ccb3e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":320},
            "size":{
              "width":349,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"801d758452e741f78d8fdc29b156e9f7",
          "label":"数据预览",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":380},
            "size":{
              "width":942,
              "height":467}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"54805bce471c48d4a4027408cd587c37",
              "label":"预览结果",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9c8710d5fd834e71ae8b8ac9c6c0a8c7",
                  "label":"",
                  "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":30},
                    "size":{
                      "width":911,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0ab5d6cec6941939726244703f0557f",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "size":{
                          "width":304,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0e3f9bb6763c4eeeb35532f4fa2a95ad",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "size":{
                              "width":304,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u65.png"}},
{
                      "id":"329f63f283ab45b7a1b92a0117f78a60",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":304,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1f05d0e4d0bb45dd9f4aeb8ff9e1d23e",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":30},
                            "size":{
                              "width":304,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u65.png"}},
{
                      "id":"f94fe832bbb242259b70981c9cb4a296",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":304,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6d37d6d5fe14440fb7da548debc1d7cd",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":60},
                            "size":{
                              "width":304,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u77.png"}},
{
                      "id":"c0b646b2e0f24801893cba4c37bb8026",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":304,
                          "y":0},
                        "size":{
                          "width":304,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bb38e96288e44e7d86f74c74689e2f99",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":304,
                              "y":0},
                            "size":{
                              "width":304,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u65.png"}},
{
                      "id":"fd13e32e869945c2a1169595f20b5f92",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":304,
                          "y":30},
                        "size":{
                          "width":304,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"731fef270721470eabcf82db80187367",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":304,
                              "y":30},
                            "size":{
                              "width":304,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u65.png"}},
{
                      "id":"8e2eb908c55a47238c31c13c3757a9f2",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":304,
                          "y":60},
                        "size":{
                          "width":304,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3ff4c300b04345cab91d84a9b9df80e9",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":304,
                              "y":60},
                            "size":{
                              "width":304,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u77.png"}},
{
                      "id":"a68d390ce14d49f48e0eda30618553a8",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":608,
                          "y":0},
                        "size":{
                          "width":303,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9ea6fc5c6b94454fb47b056893249299",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":608,
                              "y":0},
                            "size":{
                              "width":303,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u69.png"}},
{
                      "id":"023bb1abd9f041109be6f49189c35a79",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":608,
                          "y":30},
                        "size":{
                          "width":303,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9044f20940cb40cc8467693e00f94707",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":608,
                              "y":30},
                            "size":{
                              "width":303,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u69.png"}},
{
                      "id":"9a38ce5c826c49cc8d110abf027527ad",
                      "label":"",
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":608,
                          "y":60},
                        "size":{
                          "width":303,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"02a89a986364430a9ffa129659bfe643",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":608,
                              "y":60},
                            "size":{
                              "width":303,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/添加新的数据集-code/u81.png"}}]}]},
{
              "id":"3672ac6fe77f4295b22b7015a023aeb1",
              "label":"join选项",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4074fe612e2342f69381e63ebf33dd88",
                  "label":"",
                  "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                  "type":"listBox",
                  "styleType":"listBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":20},
                    "size":{
                      "width":280,
                      "height":170}},
                  "adaptiveStyles":{
}},
{
                  "id":"3ef098accabc45ac9ae812b533c1ba19",
                  "label":"",
                  "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":440,
                      "y":90},
                    "size":{
                      "width":35,
                      "height":29},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b2f1f947129447d84e4967b6382e189",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":440,
                          "y":90},
                        "size":{
                          "width":35,
                          "height":29},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/添加新的数据集-code/u84.png"}},
{
                  "id":"52a93cafdf3345ac813fd3844d3fac16",
                  "label":"",
                  "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                  "type":"listBox",
                  "styleType":"listBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":520,
                      "y":20},
                    "size":{
                      "width":280,
                      "height":170}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onSelectionChange":{
                      "description":"OnSelectionChange",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set join结果 to join结果",
                              "panelsToStates":[{
                                  "panelPath":["f6ff507372404bea805ab27d04ac6b27"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}}},
{
                  "id":"f6ff507372404bea805ab27d04ac6b27",
                  "label":"join结果",
                  "parentDynamicPanel":"801d758452e741f78d8fdc29b156e9f7",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":60,
                      "y":240},
                    "size":{
                      "width":800,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"81d85a3b6f18444086ee7616c2ceff0b",
                      "label":"null",
                      "type":"Axure:PanelDiagram",
                      "objects":[]},
{
                      "id":"d9d298d442cb4f0c9e34713511600102",
                      "label":"join结果",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"6e84c0ce6e6d41a4a13da13d4ca6bedc",
                          "label":"",
                          "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                          "type":"table",
                          "styleType":"table",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":21,
                              "y":40},
                            "size":{
                              "width":729,
                              "height":80}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e9080cf4991747209ad192cc05e083cb",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "size":{
                                  "width":182,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"a330bdc934e54194882727ce9ff5f683",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "size":{
                                      "width":182,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u89.png"}},
{
                              "id":"30377d9315664d69a95f1b82daea76e7",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":0,
                                  "y":30},
                                "size":{
                                  "width":182,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"b622b76deb6d49b9853a34adc8e2737d",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":0,
                                      "y":30},
                                    "size":{
                                      "width":182,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u89.png"}},
{
                              "id":"397de2bf08cf4eb7893ef25d46f6360a",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":0,
                                  "y":60},
                                "size":{
                                  "width":182,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"4c6d3c688aa24b5b8a499a76ed55fa71",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":0,
                                      "y":60},
                                    "size":{
                                      "width":182,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u105.png"}},
{
                              "id":"3e212ece55294bd8b982cf8f6562c2fc",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":182,
                                  "y":0},
                                "size":{
                                  "width":182,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"15b19d2ee3a74f48ba6fc74d0c1d27ea",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":182,
                                      "y":0},
                                    "size":{
                                      "width":182,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u89.png"}},
{
                              "id":"26152a5a394a4ae1840dc25a91ec0d0f",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":182,
                                  "y":30},
                                "size":{
                                  "width":182,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"ffe04a433b074512ab8a994719f3ba2d",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":182,
                                      "y":30},
                                    "size":{
                                      "width":182,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u89.png"}},
{
                              "id":"2725a0d64f254d20b37efa832040046f",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":182,
                                  "y":60},
                                "size":{
                                  "width":182,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"4289d7540c6249f58624939a14ca424f",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":182,
                                      "y":60},
                                    "size":{
                                      "width":182,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u105.png"}},
{
                              "id":"735de1a7084d480daeb215dcf11de498",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":546,
                                  "y":0},
                                "size":{
                                  "width":183,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"4baad72e76c14530afe1adcbe1e3cded",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":546,
                                      "y":0},
                                    "size":{
                                      "width":183,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u95.png"}},
{
                              "id":"66d451f8ccf84fec9f8e48f2cf97180c",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":546,
                                  "y":30},
                                "size":{
                                  "width":183,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"0b2e51bde6774d0892c1a0773c3dfa4c",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":546,
                                      "y":30},
                                    "size":{
                                      "width":183,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u95.png"}},
{
                              "id":"77e0ad2b812e48ee81962aa92ec6bd16",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":546,
                                  "y":60},
                                "size":{
                                  "width":183,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"f5d05c21a1fb4263976a18c46360091a",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":546,
                                      "y":60},
                                    "size":{
                                      "width":183,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u111.png"}},
{
                              "id":"329d942fe0064bf7bd285583129044ba",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":364,
                                  "y":0},
                                "size":{
                                  "width":182,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"4b1db40954404d62a9b94063a7be76b1",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":364,
                                      "y":0},
                                    "size":{
                                      "width":182,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u89.png"}},
{
                              "id":"0e4f832b8c9d4980b118da4ae8388c20",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":364,
                                  "y":30},
                                "size":{
                                  "width":182,
                                  "height":30}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"ffb7c96759694d33b44d165c1ee864fb",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":364,
                                      "y":30},
                                    "size":{
                                      "width":182,
                                      "height":30}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u89.png"}},
{
                              "id":"9722adb99f6b47c4be1c0a2b75e9e348",
                              "label":"",
                              "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                              "type":"tableCell",
                              "styleType":"tableCell",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"center",
                                "verticalAlignment":"middle",
                                "location":{
                                  "x":364,
                                  "y":60},
                                "size":{
                                  "width":182,
                                  "height":20}},
                              "adaptiveStyles":{
},
                              "objects":[{
                                  "id":"a6eda94965d14159b94e5c13fa62d683",
                                  "label":"",
                                  "isContained":true,
                                  "parentDynamicPanel":"f6ff507372404bea805ab27d04ac6b27",
                                  "type":"richTextPanel",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "horizontalAlignment":"center",
                                    "verticalAlignment":"middle",
                                    "location":{
                                      "x":364,
                                      "y":60},
                                    "size":{
                                      "width":182,
                                      "height":20}},
                                  "adaptiveStyles":{
}}],
                              "images":{
                                "normal~":"images/添加新的数据集-code/u105.png"}}]}]}]}]},
{
              "id":"4b1b0c0576c84675b7db784475b35752",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]}]}},
  "masters":{
    "5542c2b03c214be0825ca9668913f769":{
      "packageId":"5542c2b03c214be0825ca9668913f769",
      "type":"Axure:Master",
      "name":"公共头部-已登录",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0485693d3903489ba50d27ec5c2da9b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":1180,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5c3b2396b92b4313b10cd10aa5f0a153",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":1180,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u3.png"}},
{
            "id":"3bcafff37ae64af2bea60047cfc6b6d6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":15},
              "size":{
                "width":40,
                "height":40},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"58e79641c93d441f861049198e19d942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1110,
                    "y":15},
                  "size":{
                    "width":40,
                    "height":40},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set 用户设置 to 菜单",
                        "panelsToStates":[{
                            "panelPath":["93eca07adb4e4fc4a41d614d18498197"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/connector__/u5.png"}},
{
            "id":"6514f50dd3fb4774aa20904f345237fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":21},
              "size":{
                "width":145,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fe7e681127c444418e4e3ba5d45d8b7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":21},
                  "size":{
                    "width":145,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3788ab7d7eb6473fb90f6b3d04c9d4a0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1054,
                "y":19},
              "size":{
                "width":35,
                "height":35},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fedf1a1b475d4ecd8c4286b504e1ecd2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1054,
                    "y":19},
                  "size":{
                    "width":35,
                    "height":35},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u9.png"}},
{
            "id":"3057107345934e169d773a87fd4ca5bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFF,
                "opacity":0},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":1075,
                "y":18},
              "size":{
                "width":10,
                "height":10},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a4c1ffc855e48eb89325e8821ce3673",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF,
                    "opacity":0},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":1075,
                    "y":18},
                  "size":{
                    "width":10,
                    "height":10},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/connector__/u11.png"}},
{
            "id":"28baee9b1f8d490f84c240cd46dba014",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":238,
                "y":27},
              "size":{
                "width":29,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f183fe51e0764fe6aba4768b04474e66",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":238,
                    "y":27},
                  "size":{
                    "width":29,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"97dc0897c185427db74e6a3d9af0e4f4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":337,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aad64ad92a34411a81170d03e47b3695",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":337,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37187d0cb1cd4788aff96082b2fce88f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":463,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5990d77a0fed46efab899c51311831a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":463,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f714a97a54e2460985f688450813581f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":590,
                "y":27},
              "size":{
                "width":57,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a6babad0b20c4058ae55e4f79d5d8e90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":590,
                    "y":27},
                  "size":{
                    "width":57,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"93eca07adb4e4fc4a41d614d18498197",
            "label":"用户设置",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":1110,
                "y":55},
              "size":{
                "width":140,
                "height":115}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"105d9e067c434de9882fa01917671576",
                "label":"null",
                "type":"Axure:PanelDiagram",
                "objects":[]},
{
                "id":"b080cbd4cc694748aa3f7b2264e72103",
                "label":"菜单",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"42b31ce597d64e1fb85bc5a4fdd210dd",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":140,
                        "height":120}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fe776c44550c494992797a165259f471",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":140,
                            "height":120}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u22.png"}},
{
                    "id":"060533122f194eee8fbb0026893375b6",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":20},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bc5eacb229ca428b8591c2787768feb8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":20},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 用户管理 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cbc3eeec59b24953b61c5b5d250862a8",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":43,
                        "y":60},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"04a58d5632a14fac89a109a4119b7c15",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":43,
                            "y":60},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open 租户信息 in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"租户信息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"430a0eeff6c54ed4bfb3c33b50af8441",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":21},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1c09b8589ca346ba81e5a7a12f543362",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":21},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u28.png"}},
{
                    "id":"5a0767b803ff48b383c34492015edc99",
                    "label":"",
                    "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":15,
                        "y":60},
                      "size":{
                        "width":15,
                        "height":15},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c7c54ebc78514d33bbcc9ade17e1599d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"93eca07adb4e4fc4a41d614d18498197",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":15,
                            "y":60},
                          "size":{
                            "width":15,
                            "height":15},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/connector__/u30.png"}}]}]}]}}},
  "objectPaths":{
    "ca573c50a3a64d9db2529eacf5104b69":{
      "scriptId":"u0"},
    "50c549d8773a4361be4db2bdc2dbb6d8":{
      "scriptId":"u1"},
    "79006635523f495c8be17591d4b4d4f6":{
      "scriptId":"u2",
      "0485693d3903489ba50d27ec5c2da9b8":{
        "scriptId":"u3"},
      "5c3b2396b92b4313b10cd10aa5f0a153":{
        "scriptId":"u4"},
      "3bcafff37ae64af2bea60047cfc6b6d6":{
        "scriptId":"u5"},
      "58e79641c93d441f861049198e19d942":{
        "scriptId":"u6"},
      "6514f50dd3fb4774aa20904f345237fc":{
        "scriptId":"u7"},
      "fe7e681127c444418e4e3ba5d45d8b7e":{
        "scriptId":"u8"},
      "3788ab7d7eb6473fb90f6b3d04c9d4a0":{
        "scriptId":"u9"},
      "fedf1a1b475d4ecd8c4286b504e1ecd2":{
        "scriptId":"u10"},
      "3057107345934e169d773a87fd4ca5bf":{
        "scriptId":"u11"},
      "0a4c1ffc855e48eb89325e8821ce3673":{
        "scriptId":"u12"},
      "28baee9b1f8d490f84c240cd46dba014":{
        "scriptId":"u13"},
      "f183fe51e0764fe6aba4768b04474e66":{
        "scriptId":"u14"},
      "97dc0897c185427db74e6a3d9af0e4f4":{
        "scriptId":"u15"},
      "aad64ad92a34411a81170d03e47b3695":{
        "scriptId":"u16"},
      "37187d0cb1cd4788aff96082b2fce88f":{
        "scriptId":"u17"},
      "5990d77a0fed46efab899c51311831a8":{
        "scriptId":"u18"},
      "f714a97a54e2460985f688450813581f":{
        "scriptId":"u19"},
      "a6babad0b20c4058ae55e4f79d5d8e90":{
        "scriptId":"u20"},
      "93eca07adb4e4fc4a41d614d18498197":{
        "scriptId":"u21"},
      "42b31ce597d64e1fb85bc5a4fdd210dd":{
        "scriptId":"u22"},
      "fe776c44550c494992797a165259f471":{
        "scriptId":"u23"},
      "060533122f194eee8fbb0026893375b6":{
        "scriptId":"u24"},
      "bc5eacb229ca428b8591c2787768feb8":{
        "scriptId":"u25"},
      "cbc3eeec59b24953b61c5b5d250862a8":{
        "scriptId":"u26"},
      "04a58d5632a14fac89a109a4119b7c15":{
        "scriptId":"u27"},
      "430a0eeff6c54ed4bfb3c33b50af8441":{
        "scriptId":"u28"},
      "1c09b8589ca346ba81e5a7a12f543362":{
        "scriptId":"u29"},
      "5a0767b803ff48b383c34492015edc99":{
        "scriptId":"u30"},
      "c7c54ebc78514d33bbcc9ade17e1599d":{
        "scriptId":"u31"}},
    "8e32edc47a9a4a018a9d3a06ee4c8f34":{
      "scriptId":"u32"},
    "1e64da9f31f54d23af4d4b6b1666a1dc":{
      "scriptId":"u33"},
    "4ed39a9849304a18bd4eaf57c3c1be70":{
      "scriptId":"u34"},
    "d2865a9a969f4b3d940a0efad5806798":{
      "scriptId":"u35"},
    "0996fc24852641f7961f34a74754b095":{
      "scriptId":"u36"},
    "3f9c5be30fe0424889240815b5d4638f":{
      "scriptId":"u37"},
    "8cc8aa6a01f9474e9a004a8e42d2ed5e":{
      "scriptId":"u38"},
    "dbb6424043f04834a86e6483d7623492":{
      "scriptId":"u39"},
    "4fb997e009fd4111a0b8fe8e35d373f7":{
      "scriptId":"u40"},
    "f5fd9f79a1ad4457b991092f96c03368":{
      "scriptId":"u41"},
    "78fd0bfe454740f287a830dfa71dd7ce":{
      "scriptId":"u42"},
    "dbaa83e228ef4c5ca0fec92fc49c219d":{
      "scriptId":"u43"},
    "fccbcd2560d843e9834de44ae79c9f3d":{
      "scriptId":"u44"},
    "c0172a50b75e4c88b1c3ac9bb64e2419":{
      "scriptId":"u45"},
    "54617edb9c644e18abc3c8e162aead2b":{
      "scriptId":"u46"},
    "a2a747cf133c4e8ab60b02838b27f581":{
      "scriptId":"u47"},
    "5f2ef16542ed4ab1966b910ababc57f0":{
      "scriptId":"u48"},
    "c642930c5b084844a0fa2e2ee738c6d3":{
      "scriptId":"u49"},
    "6e6a1f4f0c054426b70a1e3c8b0c478d":{
      "scriptId":"u50"},
    "115990202db9497ead1635456794ce36":{
      "scriptId":"u51"},
    "53aef586ae204894a3b7cf6bb76746cc":{
      "scriptId":"u52"},
    "058ad97e9437426c98f1eebd4d7b6766":{
      "scriptId":"u53"},
    "0762b1c0f4204857bf9b328d7fa824b4":{
      "scriptId":"u54"},
    "1df6057aa46646b4a1d592a42034c5aa":{
      "scriptId":"u55"},
    "175e03766e81480f989ac3bbfd53a631":{
      "scriptId":"u56"},
    "9686845298c34cfda2293503aef3c429":{
      "scriptId":"u57"},
    "d1cbdcfa2e874416980e56484234da2c":{
      "scriptId":"u58"},
    "7245a12a8c1941cc93f0b6f1fec9c23a":{
      "scriptId":"u59"},
    "d332509f4a2e41e3881667d21971390c":{
      "scriptId":"u60"},
    "ead7c49a4c6e4efca0484170694b25fd":{
      "scriptId":"u61"},
    "00120108bf904733a8ed0fbe8f9ccb3e":{
      "scriptId":"u62"},
    "801d758452e741f78d8fdc29b156e9f7":{
      "scriptId":"u63"},
    "9c8710d5fd834e71ae8b8ac9c6c0a8c7":{
      "scriptId":"u64"},
    "c0ab5d6cec6941939726244703f0557f":{
      "scriptId":"u65"},
    "0e3f9bb6763c4eeeb35532f4fa2a95ad":{
      "scriptId":"u66"},
    "c0b646b2e0f24801893cba4c37bb8026":{
      "scriptId":"u67"},
    "bb38e96288e44e7d86f74c74689e2f99":{
      "scriptId":"u68"},
    "a68d390ce14d49f48e0eda30618553a8":{
      "scriptId":"u69"},
    "9ea6fc5c6b94454fb47b056893249299":{
      "scriptId":"u70"},
    "329f63f283ab45b7a1b92a0117f78a60":{
      "scriptId":"u71"},
    "1f05d0e4d0bb45dd9f4aeb8ff9e1d23e":{
      "scriptId":"u72"},
    "fd13e32e869945c2a1169595f20b5f92":{
      "scriptId":"u73"},
    "731fef270721470eabcf82db80187367":{
      "scriptId":"u74"},
    "023bb1abd9f041109be6f49189c35a79":{
      "scriptId":"u75"},
    "9044f20940cb40cc8467693e00f94707":{
      "scriptId":"u76"},
    "f94fe832bbb242259b70981c9cb4a296":{
      "scriptId":"u77"},
    "6d37d6d5fe14440fb7da548debc1d7cd":{
      "scriptId":"u78"},
    "8e2eb908c55a47238c31c13c3757a9f2":{
      "scriptId":"u79"},
    "3ff4c300b04345cab91d84a9b9df80e9":{
      "scriptId":"u80"},
    "9a38ce5c826c49cc8d110abf027527ad":{
      "scriptId":"u81"},
    "02a89a986364430a9ffa129659bfe643":{
      "scriptId":"u82"},
    "4074fe612e2342f69381e63ebf33dd88":{
      "scriptId":"u83"},
    "3ef098accabc45ac9ae812b533c1ba19":{
      "scriptId":"u84"},
    "1b2f1f947129447d84e4967b6382e189":{
      "scriptId":"u85"},
    "52a93cafdf3345ac813fd3844d3fac16":{
      "scriptId":"u86"},
    "f6ff507372404bea805ab27d04ac6b27":{
      "scriptId":"u87"},
    "6e84c0ce6e6d41a4a13da13d4ca6bedc":{
      "scriptId":"u88"},
    "e9080cf4991747209ad192cc05e083cb":{
      "scriptId":"u89"},
    "a330bdc934e54194882727ce9ff5f683":{
      "scriptId":"u90"},
    "3e212ece55294bd8b982cf8f6562c2fc":{
      "scriptId":"u91"},
    "15b19d2ee3a74f48ba6fc74d0c1d27ea":{
      "scriptId":"u92"},
    "329d942fe0064bf7bd285583129044ba":{
      "scriptId":"u93"},
    "4b1db40954404d62a9b94063a7be76b1":{
      "scriptId":"u94"},
    "735de1a7084d480daeb215dcf11de498":{
      "scriptId":"u95"},
    "4baad72e76c14530afe1adcbe1e3cded":{
      "scriptId":"u96"},
    "30377d9315664d69a95f1b82daea76e7":{
      "scriptId":"u97"},
    "b622b76deb6d49b9853a34adc8e2737d":{
      "scriptId":"u98"},
    "26152a5a394a4ae1840dc25a91ec0d0f":{
      "scriptId":"u99"},
    "ffe04a433b074512ab8a994719f3ba2d":{
      "scriptId":"u100"},
    "0e4f832b8c9d4980b118da4ae8388c20":{
      "scriptId":"u101"},
    "ffb7c96759694d33b44d165c1ee864fb":{
      "scriptId":"u102"},
    "66d451f8ccf84fec9f8e48f2cf97180c":{
      "scriptId":"u103"},
    "0b2e51bde6774d0892c1a0773c3dfa4c":{
      "scriptId":"u104"},
    "397de2bf08cf4eb7893ef25d46f6360a":{
      "scriptId":"u105"},
    "4c6d3c688aa24b5b8a499a76ed55fa71":{
      "scriptId":"u106"},
    "2725a0d64f254d20b37efa832040046f":{
      "scriptId":"u107"},
    "4289d7540c6249f58624939a14ca424f":{
      "scriptId":"u108"},
    "9722adb99f6b47c4be1c0a2b75e9e348":{
      "scriptId":"u109"},
    "a6eda94965d14159b94e5c13fa62d683":{
      "scriptId":"u110"},
    "77e0ad2b812e48ee81962aa92ec6bd16":{
      "scriptId":"u111"},
    "f5d05c21a1fb4263976a18c46360091a":{
      "scriptId":"u112"}}});