$axure.loadCurrentPage({
  "url":"关于支持的图表类型说明.html",
  "generationDate":new Date(1479293544183.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ad6406ad3cd9454b98a4b366a27d1728",
    "type":"Axure:Page",
    "name":"关于支持的图表类型说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0317bc1be9db494c9ff1897b10f0cd60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":24},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ca06c4538f429aa3be9194d0dc91c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":24},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93c7f9a7660746fda5e22ab001d188ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":80},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41b22c403a7b4597807bcc2339f89737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":80},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ad9c003a1cf4229891edbab4585eedb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":133},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bf072450a8b42cead208de137de495f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":133},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62e95d7b5c1c428e8f4dc9096630a96d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":186},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4f7065c5e5410e9e4fd181324a7bbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":186},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"029f0848f07b4161910b8cefaad38473",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":232},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7a399b5870b4972a2025472e740dfcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":232},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acaf353eecfc44be88d54400d5cb8eaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":278},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf53993feffc4bd8a62c761414741895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":278},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2394251d60494812be25c4a46dc11859",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":415},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70fe2742abec439e88eed1d4a9df8c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":415},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cc2a3123886435fb1dccce31880663b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":324},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de4a1c19a2e4830af3896e45506403f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":324},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c2b0d9aef964a72accab2ed9edb2075",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":364},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"662a9a36feb748c9a539403994fa65c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":364},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5422686412f43e1bada93016f169e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":494},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c6d72cf80a418c8a7356e8eea837af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":494},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ca63adfd5004dbb8039c0c3a02ae2ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":534},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d509eac3054e8aa489b498258ad240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":534},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d42774802734a12957c69dbe8505c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":456},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3acb1b03997542829d593afc971f62b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":456},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0317bc1be9db494c9ff1897b10f0cd60":{
      "scriptId":"u0"},
    "f6ca06c4538f429aa3be9194d0dc91c4":{
      "scriptId":"u1"},
    "93c7f9a7660746fda5e22ab001d188ed":{
      "scriptId":"u2"},
    "41b22c403a7b4597807bcc2339f89737":{
      "scriptId":"u3"},
    "9ad9c003a1cf4229891edbab4585eedb":{
      "scriptId":"u4"},
    "5bf072450a8b42cead208de137de495f":{
      "scriptId":"u5"},
    "62e95d7b5c1c428e8f4dc9096630a96d":{
      "scriptId":"u6"},
    "ab4f7065c5e5410e9e4fd181324a7bbe":{
      "scriptId":"u7"},
    "029f0848f07b4161910b8cefaad38473":{
      "scriptId":"u8"},
    "a7a399b5870b4972a2025472e740dfcc":{
      "scriptId":"u9"},
    "acaf353eecfc44be88d54400d5cb8eaa":{
      "scriptId":"u10"},
    "bf53993feffc4bd8a62c761414741895":{
      "scriptId":"u11"},
    "2394251d60494812be25c4a46dc11859":{
      "scriptId":"u12"},
    "70fe2742abec439e88eed1d4a9df8c0d":{
      "scriptId":"u13"},
    "4cc2a3123886435fb1dccce31880663b":{
      "scriptId":"u14"},
    "0de4a1c19a2e4830af3896e45506403f":{
      "scriptId":"u15"},
    "0c2b0d9aef964a72accab2ed9edb2075":{
      "scriptId":"u16"},
    "662a9a36feb748c9a539403994fa65c8":{
      "scriptId":"u17"},
    "a5422686412f43e1bada93016f169e29":{
      "scriptId":"u18"},
    "f3c6d72cf80a418c8a7356e8eea837af":{
      "scriptId":"u19"},
    "5ca63adfd5004dbb8039c0c3a02ae2ad":{
      "scriptId":"u20"},
    "e4d509eac3054e8aa489b498258ad240":{
      "scriptId":"u21"},
    "3d42774802734a12957c69dbe8505c52":{
      "scriptId":"u22"},
    "3acb1b03997542829d593afc971f62b5":{
      "scriptId":"u23"}}});